#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Thu Sep 10 13:32:33 2009

import wx

# begin wxGlade: extracode
# end wxGlade



class CreateRecordDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.Referral_Label = wx.StaticText(self, -1, "REFERRAL", style=wx.ALIGN_CENTRE)
        self.ReferralTopic_Label = wx.StaticText(self, -1, "Topic of Referral:")
        self.ReferralTopic_TextCtrl = wx.TextCtrl(self, -1, "topic of referral")
        self.ReferralReason_Label = wx.StaticText(self, -1, "Reason of Referral:")
        self.ReferralReason_Combo = wx.ComboBox(self, -1, choices=["Case", "Incident", "Request"], style=wx.CB_DROPDOWN|wx.CB_READONLY|wx.CB_SORT)
        self.static_line_3 = wx.StaticLine(self, -1)
        self.PatientInfo_Label = wx.StaticText(self, -1, "PATIENT INFORMATION", style=wx.ALIGN_CENTRE)
        self.PatientFirstName_Label = wx.StaticText(self, -1, "First Name:")
        self.PatientFirstName_TextCtrl = wx.TextCtrl(self, -1, "first name")
        self.PatientMiddleName_Label = wx.StaticText(self, -1, "Middle Name:")
        self.PatientMiddleName_TextCtrl = wx.TextCtrl(self, -1, "middle name")
        self.PatientLastName_Label = wx.StaticText(self, -1, "Last Name:")
        self.PatientLastName_TextCtrl = wx.TextCtrl(self, -1, "last name")
        self.PatientGender_Label = wx.StaticText(self, -1, "Gender:")
        self.PatientGender_Combo = wx.ComboBox(self, -1, choices=["Female", "Male"], style=wx.CB_DROPDOWN|wx.CB_READONLY|wx.CB_SORT)
        self.PatientAge_Label = wx.StaticText(self, -1, "Age:")
        self.PatientAge_TextCtrl = wx.TextCtrl(self, -1, "age")
        self.PatientAgeDMY_Combo = wx.ComboBox(self, -1, choices=["Days", "Months", "Years"], style=wx.CB_DROPDOWN|wx.CB_READONLY|wx.CB_SORT)
        self.PatientAgeValidity_Combo = wx.ComboBox(self, -1, choices=["Known", "Unknown", "Estimated"], style=wx.CB_DROPDOWN|wx.CB_READONLY|wx.CB_SORT)
        self.PatientAddress_Label = wx.StaticText(self, -1, "Address:")
        self.PatientAddress_TextCtrl = wx.TextCtrl(self, -1, "address", style=wx.TE_MULTILINE)
        self.PatientPhoneNumber_Label = wx.StaticText(self, -1, "Phone Number:")
        self.PatientPhoneNumber_TextCtrl = wx.TextCtrl(self, -1, "phone number")
        self.static_line_4 = wx.StaticLine(self, -1)
        self.Remark = wx.StaticText(self, -1, "Remarks:")
        self.RemarkValue = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE)
        self.CreatePatient_Button = wx.Button(self, -1, "CREATE RECORD")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnCreateRecord, self.CreatePatient_Button)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyDialog.__set_properties
        self.SetTitle("Create Patient Record")
        self.ReferralReason_Combo.SetSelection(-1)
        self.PatientGender_Combo.SetSelection(-1)
        self.PatientAgeDMY_Combo.SetSelection(0)
        self.PatientAgeValidity_Combo.SetSelection(0)
        self.RemarkValue.SetMinSize((481, 77))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyDialog.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_24 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.FlexGridSizer(1, 4, 0, 0)
        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        sizer_14 = wx.FlexGridSizer(1, 4, 0, 0)
        sizer_13 = wx.FlexGridSizer(1, 4, 0, 0)
        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11 = wx.FlexGridSizer(1, 4, 0, 0)
        sizer_10 = wx.FlexGridSizer(1, 4, 0, 0)
        sizer_9 = wx.FlexGridSizer(1, 4, 0, 0)
        sizer_8 = wx.FlexGridSizer(1, 4, 0, 0)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_6 = wx.FlexGridSizer(1, 4, 0, 0)
        sizer_5 = wx.FlexGridSizer(1, 4, 0, 0)
        sizer_3.Add(self.Referral_Label, 0, wx.ALL|wx.EXPAND, 4)
        sizer_5.Add(self.ReferralTopic_Label, 0, wx.ALL, 4)
        sizer_5.Add((30, 20), 0, 0, 0)
        sizer_5.Add(self.ReferralTopic_TextCtrl, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 4)
        sizer_5.Add((20, 20), 0, 0, 0)
        sizer_5.AddGrowableCol(2)
        sizer_3.Add(sizer_5, 1, wx.EXPAND, 0)
        sizer_6.Add(self.ReferralReason_Label, 0, wx.ALL, 4)
        sizer_6.Add((15, 20), 0, 0, 0)
        sizer_6.Add(self.ReferralReason_Combo, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM, 4)
        sizer_6.Add((20, 20), 0, 0, 0)
        sizer_6.AddGrowableCol(2)
        sizer_3.Add(sizer_6, 1, wx.EXPAND, 0)
        sizer_3.Add(self.static_line_3, 0, wx.EXPAND, 0)
        sizer_2.Add(sizer_3, 0, wx.EXPAND, 0)
        sizer_7.Add(self.PatientInfo_Label, 0, wx.ALL|wx.EXPAND, 4)
        sizer_8.Add(self.PatientFirstName_Label, 0, wx.ALL, 4)
        sizer_8.Add((60, 20), 0, 0, 0)
        sizer_8.Add(self.PatientFirstName_TextCtrl, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 4)
        sizer_8.Add((20, 20), 0, 0, 0)
        sizer_8.AddGrowableCol(2)
        sizer_7.Add(sizer_8, 0, wx.EXPAND, 0)
        sizer_9.Add(self.PatientMiddleName_Label, 0, wx.ALL, 4)
        sizer_9.Add((47, 20), 0, 0, 0)
        sizer_9.Add(self.PatientMiddleName_TextCtrl, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 4)
        sizer_9.Add((120, 20), 0, 0, 0)
        sizer_9.AddGrowableCol(2)
        sizer_7.Add(sizer_9, 1, wx.EXPAND, 0)
        sizer_10.Add(self.PatientLastName_Label, 0, wx.ALL, 4)
        sizer_10.Add((61, 20), 0, 0, 0)
        sizer_10.Add(self.PatientLastName_TextCtrl, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 4)
        sizer_10.Add((120, 20), 0, 0, 0)
        sizer_10.AddGrowableCol(2)
        sizer_7.Add(sizer_10, 0, wx.EXPAND, 0)
        sizer_11.Add(self.PatientGender_Label, 0, wx.ALL, 4)
        sizer_11.Add((84, 20), 0, 0, 0)
        sizer_11.Add(self.PatientGender_Combo, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM, 4)
        sizer_11.Add((20, 20), 0, 0, 0)
        sizer_11.AddGrowableCol(2)
        sizer_7.Add(sizer_11, 0, wx.EXPAND, 0)
        sizer_12.Add(self.PatientAge_Label, 0, wx.ALL, 4)
        sizer_12.Add((101, 20), 0, 0, 0)
        sizer_12.Add(self.PatientAge_TextCtrl, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM, 4)
        sizer_12.Add(self.PatientAgeDMY_Combo, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM, 4)
        sizer_12.Add(self.PatientAgeValidity_Combo, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM, 4)
        sizer_12.Add((20, 20), 0, 0, 0)
        sizer_7.Add(sizer_12, 1, wx.EXPAND, 0)
        sizer_13.Add(self.PatientAddress_Label, 0, wx.ALL, 4)
        sizer_13.Add((72, 20), 0, 0, 0)
        sizer_13.Add(self.PatientAddress_TextCtrl, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 4)
        sizer_13.Add((20, 20), 0, 0, 0)
        sizer_13.AddGrowableCol(2)
        sizer_7.Add(sizer_13, 0, wx.EXPAND, 0)
        sizer_14.Add(self.PatientPhoneNumber_Label, 0, wx.ALL, 4)
        sizer_14.Add((27, 20), 0, 0, 0)
        sizer_14.Add(self.PatientPhoneNumber_TextCtrl, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM, 4)
        sizer_14.Add((20, 20), 0, 0, 0)
        sizer_14.AddGrowableCol(2)
        sizer_7.Add(sizer_14, 0, wx.EXPAND, 0)
        sizer_7.Add(self.static_line_4, 0, wx.EXPAND, 0)
        sizer_2.Add(sizer_7, 0, wx.EXPAND, 0)
        sizer_4.Add(self.Remark, 0, 0, 0)
        sizer_4.Add((80, 20), 0, 0, 0)
        sizer_4.Add(self.RemarkValue, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 0)
        sizer_4.Add((20, 20), 0, 0, 0)
        sizer_2.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_24.Add((150, 20), 0, 0, 0)
        sizer_24.Add((160, 20), 0, 0, 0)
        sizer_24.Add(self.CreatePatient_Button, 0, wx.ALL, 4)
        sizer_24.Add((20, 20), 0, 0, 0)
        sizer_2.Add(sizer_24, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def OnCreateRecord(self, event): # wxGlade: MyDialog.<event_handler>
        print "Event handler `OnCreateRecord' not implemented!"
        event.Skip()

# end of class MyDialog


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    CreateRecord = MyDialog(None, -1, "")
    app.SetTopWindow(CreateRecord)
    CreateRecord.Show()
    app.MainLoop()
