#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Thu Jan  7 15:01:38 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class RxFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: RxFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.devices_panel = wx.Panel(self, -1)
        self.RxFrame_StatusBar = self.CreateStatusBar(1, 0)
        self.PatientInfoHeader_Label = wx.StaticText(self, -1, "Patient Information", style=wx.ALIGN_CENTRE|wx.ST_NO_AUTORESIZE)
        self.LastName = wx.StaticText(self, -1, "Name Last:  ")
        self.LastNameValue = wx.TextCtrl(self, -1, "")
        self.FirstName = wx.StaticText(self, -1, "   First:   ")
        self.FirstNameValue = wx.TextCtrl(self, -1, "")
        self.MiddleName = wx.StaticText(self, -1, "   Middle:   ")
        self.MiddleNameValue = wx.TextCtrl(self, -1, "")
        self.Address = wx.StaticText(self, -1, "Address:      ")
        self.AddressValue = wx.TextCtrl(self, -1, "")
        self.PhoneNumber = wx.StaticText(self, -1, "    Phone Number:   ")
        self.PhoneNumberValue = wx.TextCtrl(self, -1, "")
        self.Birthdate = wx.StaticText(self, -1, "Birthdate:    ")
        self.BirthMonth = wx.ComboBox(self, -1, choices=["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"], style=wx.CB_DROPDOWN|wx.CB_SIMPLE|wx.CB_DROPDOWN|wx.CB_READONLY)
        self.BirthDayCombo = wx.ComboBox(self, -1, choices=["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"], style=wx.CB_DROPDOWN|wx.CB_READONLY)
        self.BirthYear = wx.TextCtrl(self, -1, "")
        self.Age = wx.StaticText(self, -1, "    Age: ")
        self.AgeValue = wx.TextCtrl(self, -1, "")
        self.AgeCombo = wx.ComboBox(self, -1, choices=["Years", "Months", "Days"], style=wx.CB_DROPDOWN|wx.CB_DROPDOWN|wx.CB_READONLY)
        self.Gender = wx.StaticText(self, -1, "    Gender: ")
        self.GenderCombo = wx.ComboBox(self, -1, choices=["Male", "Female"], style=wx.CB_DROPDOWN|wx.CB_DROPDOWN|wx.CB_READONLY)
        self.video_panel = wx.Panel(self.devices_panel, -1)
        self.snapshot_panel = wx.Panel(self.devices_panel, -1)
        self.prev_snapshot = wx.Button(self.devices_panel, -1, "<<")
        self.snapshot = wx.BitmapButton(self.devices_panel, -1, wx.Bitmap("Icons/snapshot_icon.png", wx.BITMAP_TYPE_ANY), style=wx.BU_AUTODRAW)
        self.next_snapshot = wx.Button(self.devices_panel, -1, ">>")
        self.Stethoscope_Label = wx.StaticText(self.devices_panel, -1, "Stethoscope", style=wx.ALIGN_CENTRE|wx.ST_NO_AUTORESIZE)
        self.record_button = wx.BitmapButton(self.devices_panel, -1, wx.Bitmap("Icons/button_record.png", wx.BITMAP_TYPE_ANY))
        self.play_button = wx.BitmapButton(self.devices_panel, -1, wx.Bitmap("Icons/button_play.png", wx.BITMAP_TYPE_ANY))
        self.stop_button = wx.BitmapButton(self.devices_panel, -1, wx.Bitmap("Icons/button_stop.png", wx.BITMAP_TYPE_ANY))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.onPrevSnapshot, self.prev_snapshot)
        self.Bind(wx.EVT_BUTTON, self.onSnapshot, self.snapshot)
        self.Bind(wx.EVT_BUTTON, self.onNextSnapshot, self.next_snapshot)
        self.Bind(wx.EVT_BUTTON, self.on_steth_record, self.record_button)
        self.Bind(wx.EVT_BUTTON, self.on_steth_play, self.play_button)
        self.Bind(wx.EVT_BUTTON, self.on_steth_stop, self.stop_button)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: RxFrame.__set_properties
        self.SetTitle("RxBox - Philippine General Hospital")
        self.SetSize((1280, 768))
        self.SetBackgroundColour(wx.Colour(245, 255, 207))
        self.RxFrame_StatusBar.SetStatusWidths([-1])
        # statusbar fields
        RxFrame_StatusBar_fields = ["RxBox ready..."]
        for i in range(len(RxFrame_StatusBar_fields)):
            self.RxFrame_StatusBar.SetStatusText(RxFrame_StatusBar_fields[i], i)
        self.PatientInfoHeader_Label.SetBackgroundColour(wx.Colour(219, 219, 112))
        self.PatientInfoHeader_Label.SetFont(wx.Font(10, wx.MODERN, wx.NORMAL, wx.BOLD, 0, "Arial"))
        self.LastNameValue.SetMinSize((130, 21))
        self.FirstNameValue.SetMinSize((130, 21))
        self.MiddleNameValue.SetMinSize((130, 21))
        self.AddressValue.SetMinSize((300, 21))
        self.PhoneNumberValue.SetMinSize((95, 21))
        self.BirthMonth.SetMinSize((110, 25))
        self.BirthMonth.SetSelection(0)
        self.BirthDayCombo.SetMinSize((50, 25))
        self.BirthDayCombo.SetSelection(-1)
        self.BirthYear.SetMinSize((50, 25))
        self.AgeValue.SetMinSize((30, 25))
        self.AgeCombo.SetMinSize((80, 25))
        self.AgeCombo.SetSelection(0)
        self.GenderCombo.SetMinSize((80, 25))
        self.GenderCombo.SetSelection(0)
        self.video_panel.SetMinSize((160,120))
        self.snapshot_panel.SetMinSize((120,90))
        self.prev_snapshot.SetMinSize((40,30))
        self.snapshot.SetMinSize((40,30))
        self.next_snapshot.SetMinSize((40,30))
        self.Stethoscope_Label.SetMinSize((165,40))
        self.Stethoscope_Label.SetBackgroundColour(wx.Colour(219, 219, 112))
        self.Stethoscope_Label.SetFont(wx.Font(10, wx.MODERN, wx.NORMAL, wx.BOLD, 0, "Arial"))
        self.record_button.SetSize(self.record_button.GetBestSize())
        self.play_button.SetSize(self.play_button.GetBestSize())
        self.stop_button.SetSize(self.stop_button.GetBestSize())
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: RxFrame.__do_layout
        mainvertical_sizer = wx.BoxSizer(wx.VERTICAL)
        self.mainhorizontal_sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.info_daq_sizer = wx.BoxSizer(wx.VERTICAL)
        patient_info_tab_sizer = wx.BoxSizer(wx.HORIZONTAL)
        devices_sizer = wx.FlexGridSizer(1, 3, 0, 0)
        steth_sizer1 = wx.BoxSizer(wx.HORIZONTAL)
        steth_sizer = wx.BoxSizer(wx.VERTICAL)
        steth_button_sizer = wx.BoxSizer(wx.HORIZONTAL)
        snapshot_sizer = wx.FlexGridSizer(2, 1, 0, 0)
        snapshot_button_sizer = wx.FlexGridSizer(1, 3, 0, 0)
        patient_info_sizer = wx.BoxSizer(wx.VERTICAL)
        info_sizer = wx.BoxSizer(wx.HORIZONTAL)
        patient_row_sizer = wx.BoxSizer(wx.VERTICAL)
        patient_bottom_sizer = wx.BoxSizer(wx.HORIZONTAL)
        patient_middle_sizer = wx.BoxSizer(wx.HORIZONTAL)
        patient_top_sizer = wx.BoxSizer(wx.HORIZONTAL)
        patient_info_sizer.Add(self.PatientInfoHeader_Label, 1, wx.EXPAND, 0)
        patient_top_sizer.Add(self.LastName, 0, 0, 0)
        patient_top_sizer.Add(self.LastNameValue, 0, 0, 0)
        patient_top_sizer.Add(self.FirstName, 0, 0, 0)
        patient_top_sizer.Add(self.FirstNameValue, 0, 0, 0)
        patient_top_sizer.Add(self.MiddleName, 0, 0, 0)
        patient_top_sizer.Add(self.MiddleNameValue, 0, 0, 0)
        patient_row_sizer.Add(patient_top_sizer, 1, wx.EXPAND, 0)
        patient_middle_sizer.Add(self.Address, 0, 0, 0)
        patient_middle_sizer.Add(self.AddressValue, 0, 0, 0)
        patient_middle_sizer.Add(self.PhoneNumber, 0, 0, 0)
        patient_middle_sizer.Add(self.PhoneNumberValue, 0, 0, 0)
        patient_row_sizer.Add(patient_middle_sizer, 1, wx.EXPAND, 0)
        patient_bottom_sizer.Add(self.Birthdate, 0, 0, 0)
        patient_bottom_sizer.Add(self.BirthMonth, 0, 0, 0)
        patient_bottom_sizer.Add(self.BirthDayCombo, 0, 0, 0)
        patient_bottom_sizer.Add(self.BirthYear, 0, 0, 0)
        patient_bottom_sizer.Add(self.Age, 0, 0, 0)
        patient_bottom_sizer.Add(self.AgeValue, 0, 0, 0)
        patient_bottom_sizer.Add(self.AgeCombo, 0, 0, 0)
        patient_bottom_sizer.Add(self.Gender, 0, 0, 0)
        patient_bottom_sizer.Add(self.GenderCombo, 0, 0, 0)
        patient_row_sizer.Add(patient_bottom_sizer, 1, wx.EXPAND, 0)
        info_sizer.Add(patient_row_sizer, 1, wx.EXPAND, 0)
        patient_info_sizer.Add(info_sizer, 0, wx.EXPAND, 0)
        patient_info_tab_sizer.Add(patient_info_sizer, 2, wx.EXPAND, 0)
        devices_sizer.Add(self.video_panel, 1, wx.EXPAND, 0)
        snapshot_sizer.Add(self.snapshot_panel, 1, wx.EXPAND, 0)
        snapshot_button_sizer.Add(self.prev_snapshot, 1, wx.EXPAND, 0)
        snapshot_button_sizer.Add(self.snapshot, 1, wx.EXPAND, 0)
        snapshot_button_sizer.Add(self.next_snapshot, 1, wx.EXPAND, 0)
        snapshot_sizer.Add(snapshot_button_sizer, 1, wx.EXPAND, 0)
        devices_sizer.Add(snapshot_sizer, 1, wx.EXPAND, 0)
        steth_sizer.Add(self.Stethoscope_Label, 1, 0, 0)
        steth_button_sizer.Add(self.record_button, 0, 0, 0)
        steth_button_sizer.Add(self.play_button, 0, 0, 0)
        steth_button_sizer.Add(self.stop_button, 0, 0, 0)
        steth_sizer.Add(steth_button_sizer, 1, wx.EXPAND, 0)
        steth_sizer1.Add(steth_sizer, 1, wx.EXPAND, 0)
        devices_sizer.Add(steth_sizer1, 1, wx.EXPAND, 0)
        self.devices_panel.SetSizer(devices_sizer)
        patient_info_tab_sizer.Add(self.devices_panel, 1, wx.EXPAND, 0)
        self.info_daq_sizer.Add(patient_info_tab_sizer, 0, wx.ALL|wx.EXPAND, 4)
        self.mainhorizontal_sizer.Add(self.info_daq_sizer, 3, wx.EXPAND, 0)
        mainvertical_sizer.Add(self.mainhorizontal_sizer, 1, wx.EXPAND, 0)
        self.SetSizer(mainvertical_sizer)
        self.Layout()
        self.Centre()
        # end wxGlade

    def onPrevSnapshot(self, event): # wxGlade: RxFrame.<event_handler>
        print "Event handler `onPrevSnapshot' not implemented!"
        event.Skip()

    def onSnapshot(self, event): # wxGlade: RxFrame.<event_handler>
        print "Event handler `onSnapshot' not implemented!"
        event.Skip()

    def onNextSnapshot(self, event): # wxGlade: RxFrame.<event_handler>
        print "Event handler `onNextSnapshot' not implemented!"
        event.Skip()

    def on_steth_record(self, event): # wxGlade: RxFrame.<event_handler>
        print "Event handler `on_steth_record' not implemented!"
        event.Skip()

    def on_steth_play(self, event): # wxGlade: RxFrame.<event_handler>
        print "Event handler `on_steth_play' not implemented!"
        event.Skip()

    def on_steth_stop(self, event): # wxGlade: RxFrame.<event_handler>
        print "Event handler `on_steth_stop' not implemented!"
        event.Skip()

# end of class RxFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    rx_frame = RxFrame(None, -1, "")
    app.SetTopWindow(rx_frame)
    rx_frame.Show()
    app.MainLoop()
