#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Thu Mar 19 03:46:26 2009

import wx
import Messenger

# begin wxGlade: extracode
# end wxGlade



class wxMessenger(wx.Panel, Messenger.Messenger):
    def __init__(self, jid, password, *args, **kwds):
        # begin wxGlade: wxMessenger.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
	
        self.text_ctrl_messages = wx.TextCtrl(self, -1, "", style=wx.TE_READONLY|wx.TE_MULTILINE)
        self.text_ctrl_reply = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE|wx.TE_PROCESS_ENTER)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

	Messenger.Messenger.__init__(self, self, jid, password, 'rxbox')
	self.__sender = jid
	self.__rxboxConnected = False
	self.Bind(wx.EVT_TEXT_ENTER,	self.onReplyEntered,         self.text_ctrl_reply)
	self.recipient = '2001@openfire' #temp

    def __del__(self):
	self.stop()
	self.join()

    def __set_properties(self):
        # begin wxGlade: wxMessenger.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: wxMessenger.__do_layout
        base_sizer = wx.BoxSizer(wx.VERTICAL)
        base_sizer.Add(self.text_ctrl_messages, 7, wx.EXPAND, 0)
        base_sizer.Add(self.text_ctrl_reply, 3, wx.EXPAND, 0)
        self.SetSizer(base_sizer)
        base_sizer.Fit(self)
        # end wxGlade

    def setRxBoxConnected(self, isconnected):
	self.__rxboxConnected = isconnected
    def isRxBoxConnected(self):
	return self.__rxboxConnected
	
    def onReplyEntered(self, event):
        msg = self.text_ctrl_reply.GetValue()
	self.sendMessage(msg)

    def UpdateIMText(self, msg):
	self.text_ctrl_messages.AppendText('RXBOX: ' + msg + '\n')
        self.text_ctrl_reply.Clear()

    def UpdateIMRcvText(self, msg):
	if (msg is not None):
        	self.text_ctrl_messages.AppendText('PGH: ' + msg + '\n')

# end of class wxMessenger


