"""

Project LifeLink: Model View Control for the BP GUI Test Program

Authors:    Bangoy, Mark Jan
            Sy, Luke Wicent
            Luis Sison, PhD
            ------------------------------------------------
            Instrumentation, Robotics and Control Laboratory
            University of the Philippines - Diliman
            ------------------------------------------------
            February 2010
"""




#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Thu Jan 21 15:25:10 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_3 = wx.Panel(self, -1)
        self.panel_1 = wx.Panel(self, -1)
        self.panel_2 = wx.Panel(self.panel_1, -1)
        self.bp_panel1 = wx.Panel(self, -1)
        self.biomodule_panel = wx.Panel(self, -1)
        self.panel_5 = wx.Panel(self, -1)
        self.frame_1_statusbar = self.CreateStatusBar(1, 0)
        self.label_5 = wx.StaticText(self.panel_5, -1, "RxBox", style=wx.ALIGN_RIGHT)
        self.static_line_11 = wx.StaticLine(self.panel_5, -1)
        self.biomodule_staticline = wx.StaticLine(self.biomodule_panel, -1, style=wx.LI_VERTICAL)
        self.bpNow_Button = wx.Button(self.biomodule_panel, -1, "NOW")
        self.bpbarstaticlineleft = wx.StaticLine(self.biomodule_panel, -1, style=wx.LI_VERTICAL)
        self.bpbarpanel = wx.Panel(self.biomodule_panel, -1)
        self.bpbarstaticlineright = wx.StaticLine(self.biomodule_panel, -1, style=wx.LI_VERTICAL)
        self.bp_label = wx.StaticText(self.bp_panel1, -1, "Blood Pressure", style=wx.ALIGN_CENTRE)
        self.bp_infolabel = wx.StaticText(self.bp_panel1, -1, "--")
        self.bpvalue_label = wx.StaticText(self.bp_panel1, -1, "-- / --", style=wx.ALIGN_CENTRE)
        self.bprightpanel = wx.Panel(self.bp_panel1, -1)
        self.bpunit_label = wx.StaticText(self.bp_panel1, -1, "mmHg", style=wx.ALIGN_RIGHT)
        self.bp_staticline = wx.StaticLine(self.bp_panel1, -1, style=wx.LI_VERTICAL)
        self.static_line_10 = wx.StaticLine(self, -1)
        self.static_line_6 = wx.StaticLine(self.panel_1, -1, style=wx.LI_VERTICAL)
        self.label_3 = wx.StaticText(self.panel_1, -1, "STATUS :")
        self.static_line_7 = wx.StaticLine(self.panel_1, -1, style=wx.LI_VERTICAL)
        self.BP_status = wx.StaticText(self.panel_2, -1, "One Shot -- Adult Mode -- 180mmHg")
        self.static_line_8 = wx.StaticLine(self.panel_1, -1, style=wx.LI_VERTICAL)
        self.panel_4 = wx.Panel(self.panel_1, -1)
        self.static_line_9 = wx.StaticLine(self.panel_1, -1, style=wx.LI_VERTICAL)
        self.label_4 = wx.StaticText(self.panel_3, -1, "BLOOD PRESSURE DEMO PROGRAM", style=wx.ALIGN_CENTRE)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.onBPNow, self.bpNow_Button)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("BloodPressure_FOR_LINUX")
        self.SetSize((600, 400))
        self.frame_1_statusbar.SetStatusWidths([-1])
        # statusbar fields
        frame_1_statusbar_fields = [""]
        for i in range(len(frame_1_statusbar_fields)):
            self.frame_1_statusbar.SetStatusText(frame_1_statusbar_fields[i], i)
        self.label_5.SetMinSize((211, 76))
        self.label_5.SetFont(wx.Font(40, wx.TELETYPE, wx.NORMAL, wx.BOLD, 0, "Arial Black"))
        self.panel_5.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.bpNow_Button.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.bpNow_Button.SetFont(wx.Font(12, wx.MODERN, wx.NORMAL, wx.BOLD, 0, ""))
        self.bpbarpanel.SetMinSize((20, 120))
        self.bpbarpanel.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.biomodule_panel.SetMinSize((148, 120))
        self.biomodule_panel.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.bp_label.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.bp_label.SetFont(wx.Font(9, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.bp_infolabel.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.bp_infolabel.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.bpvalue_label.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.bpvalue_label.SetFont(wx.Font(30, wx.MODERN, wx.NORMAL, wx.BOLD, 0, "Arial"))
        self.bprightpanel.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.bpunit_label.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.bpunit_label.SetFont(wx.Font(10, wx.MODERN, wx.NORMAL, wx.BOLD, 0, "Arial"))
        self.bp_panel1.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.static_line_6.SetMinSize((1, 19))
        self.label_3.SetMinSize((56, 19))
        self.label_3.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.label_3.SetFont(wx.Font(9, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, ""))
        self.static_line_7.SetMinSize((1, 19))
        self.BP_status.SetMinSize((290, 19))
        self.BP_status.SetBackgroundColour(wx.Colour(255, 255, 0))
        self.panel_2.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.static_line_8.SetMinSize((1, 19))
        self.panel_4.SetMinSize((208, 19))
        self.panel_4.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.static_line_9.SetMinSize((1, 19))
        self.panel_1.SetMinSize((600, 20))
        self.panel_1.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.label_4.SetMinSize((600, 17))
        self.label_4.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.panel_3.SetBackgroundColour(wx.Colour(226, 255, 180))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        biomodule_vertical_sizer = wx.BoxSizer(wx.VERTICAL)
        biomodule_horizontal_sizer = wx.BoxSizer(wx.HORIZONTAL)
        bp_panel1_sizer = wx.BoxSizer(wx.HORIZONTAL)
        bp_sizer = wx.BoxSizer(wx.VERTICAL)
        bplabelsizer = wx.BoxSizer(wx.HORIZONTAL)
        bp_label_sizer = wx.BoxSizer(wx.HORIZONTAL)
        biomodule_panelsizer = wx.BoxSizer(wx.HORIZONTAL)
        nowButton_horizontal_sizer = wx.BoxSizer(wx.HORIZONTAL)
        bpbarsizer = wx.BoxSizer(wx.HORIZONTAL)
        bpbarhorizontal_sizer = wx.BoxSizer(wx.HORIZONTAL)
        nowButton_vertical_sizer = wx.BoxSizer(wx.VERTICAL)
        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        sizer_7.Add(self.label_5, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_7.Add(self.static_line_11, 0, wx.EXPAND, 0)
        self.panel_5.SetSizer(sizer_7)
        sizer_3.Add(self.panel_5, 1, wx.EXPAND, 0)
        biomodule_panelsizer.Add(self.biomodule_staticline, 0, wx.EXPAND, 0)
        nowButton_vertical_sizer.Add(self.bpNow_Button, 2, wx.EXPAND, 0)
        nowButton_horizontal_sizer.Add(nowButton_vertical_sizer, 3, wx.BOTTOM|wx.EXPAND, 4)
        bpbarhorizontal_sizer.Add(self.bpbarstaticlineleft, 0, wx.EXPAND, 0)
        bpbarhorizontal_sizer.Add(self.bpbarpanel, 1, wx.EXPAND, 0)
        bpbarhorizontal_sizer.Add(self.bpbarstaticlineright, 0, wx.EXPAND, 0)
        bpbarsizer.Add(bpbarhorizontal_sizer, 1, wx.EXPAND, 0)
        nowButton_horizontal_sizer.Add(bpbarsizer, 1, wx.EXPAND, 0)
        biomodule_panelsizer.Add(nowButton_horizontal_sizer, 1, wx.EXPAND, 0)
        self.biomodule_panel.SetSizer(biomodule_panelsizer)
        biomodule_horizontal_sizer.Add(self.biomodule_panel, 2, wx.EXPAND, 0)
        bp_label_sizer.Add(self.bp_label, 2, wx.BOTTOM, 1)
        bp_label_sizer.Add(self.bp_infolabel, 3, wx.BOTTOM|wx.EXPAND, 1)
        bp_sizer.Add(bp_label_sizer, 0, wx.EXPAND, 0)
        bplabelsizer.Add(self.bpvalue_label, 1, wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        bplabelsizer.Add(self.bprightpanel, 1, wx.EXPAND, 0)
        bp_sizer.Add(bplabelsizer, 1, wx.EXPAND, 0)
        bp_sizer.Add(self.bpunit_label, 0, wx.ALIGN_RIGHT, 0)
        bp_panel1_sizer.Add(bp_sizer, 1, wx.EXPAND, 0)
        bp_panel1_sizer.Add(self.bp_staticline, 0, wx.EXPAND, 0)
        self.bp_panel1.SetSizer(bp_panel1_sizer)
        biomodule_horizontal_sizer.Add(self.bp_panel1, 2, wx.EXPAND, 0)
        biomodule_vertical_sizer.Add(biomodule_horizontal_sizer, 1, wx.EXPAND, 0)
        sizer_3.Add(biomodule_vertical_sizer, 1, wx.EXPAND, 0)
        sizer_5.Add(self.static_line_10, 0, wx.EXPAND, 0)
        sizer_6.Add(self.static_line_6, 0, 0, 0)
        sizer_6.Add(self.label_3, 0, 0, 0)
        sizer_6.Add(self.static_line_7, 0, 0, 0)
        sizer_1.Add(self.BP_status, 0, 0, 0)
        self.panel_2.SetSizer(sizer_1)
        sizer_6.Add(self.panel_2, 1, wx.EXPAND, 0)
        sizer_6.Add(self.static_line_8, 0, 0, 0)
        sizer_6.Add(self.panel_4, 1, 0, 0)
        sizer_6.Add(self.static_line_9, 0, 0, 0)
        self.panel_1.SetSizer(sizer_6)
        sizer_5.Add(self.panel_1, 0, wx.EXPAND, 0)
        sizer_2.Add(self.label_4, 2, wx.EXPAND, 0)
        self.panel_3.SetSizer(sizer_2)
        sizer_5.Add(self.panel_3, 2, wx.EXPAND, 0)
        sizer_3.Add(sizer_5, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_3)
        self.Layout()
        self.Centre()
        # end wxGlade

    def onBPNow(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `onBPNow' not implemented!"
        event.Skip()

# end of class MyFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
