#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Mon Aug 30 01:35:07 2010

import wx

# begin wxGlade: extracode
# end wxGlade

"""
GUI for the
General Information Configuration
"""

class Geninfo_config_frame(wx.Frame):
    def __init__(self,parent, *args, **kwds):
         # begin wxGlade: Geninfo_config_frame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self,parent, *args, **kwds)
        self.panel_1 = wx.Panel(parent,-1)
        self.panel_3 = wx.Panel(self.panel_1, -1)
        self.panel_2 = wx.Panel(self.panel_1, -1)
        self.static_line_1 = wx.StaticLine(self.panel_1, -1)
        self.label_7 = wx.StaticText(self.panel_1, -1, "Rxbox\nA Portable Medical Appliance that monitors\nthe health status of the patient in a remote location. \nUsing medical-grade biomedical modules, \nit measures the ECG, pulse rate, blood pressure, \nand blood-oxygen saturation.\n\n")
        self.static_line_1_copy = wx.StaticLine(self.panel_1, -1)
        self.label_8_copy_copy = wx.StaticText(self.panel_1, -1, "Version                       ")
        self.gen_versiontxt = wx.TextCtrl(self.panel_1, -1, "")
        self.static_line_1_copy_2 = wx.StaticLine(self.panel_1, -1)
        self.label_8_copy = wx.StaticText(self.panel_1, -1, "Model            ")
        self.gen_modeltxt = wx.TextCtrl(self.panel_1, -1, "")
        self.static_line_1_copy_3 = wx.StaticLine(self.panel_1, -1)
        self.label_8_copy_1 = wx.StaticText(self.panel_1, -1, "RxBox ID                    ")
        self.gen_IDtxt = wx.TextCtrl(self.panel_1, -1, "")
        self.static_line_1_copy_4 = wx.StaticLine(self.panel_1, -1)
        self.label_8_copy_1_copy = wx.StaticText(self.panel_1, -1, "Startup Scr              ")
        self.startup_checkbox = wx.CheckBox(self.panel_1, -1, "")
        self.static_line_1_copy_1 = wx.StaticLine(self.panel_1, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Geninfo_config_frame.__set_properties
        self.SetTitle("frame_1")
        self.SetSize((420, 520))
        self.panel_3.SetMinSize((420, 20))
        self.panel_2.SetMinSize((40, 500))
        self.label_8_copy_copy.SetMinSize((140, 25))
        self.gen_versiontxt.SetMinSize((150, 25))
        self.static_line_1_copy_2.SetMinSize((380, 2))
        self.label_8_copy.SetMinSize((140, 25))
        self.gen_modeltxt.SetMinSize((150, 25))
        self.label_8_copy_1.SetMinSize((140, 25))
        self.gen_IDtxt.SetMinSize((150, 25))
        self.label_8_copy_1_copy.SetMinSize((140, 25))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Geninfo_config_frame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_2_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.BoxSizer(wx.VERTICAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_12_copy_1_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11 = wx.BoxSizer(wx.VERTICAL)
        sizer_12_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_12_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self.panel_3, 0, wx.EXPAND, 0)
        sizer_2_copy.Add(self.panel_2, 0, wx.EXPAND, 0)
        sizer_9.Add(self.static_line_1, 0, wx.EXPAND, 0)
        sizer_9.Add(self.label_7, 0, 0, 0)
        sizer_9.Add(self.static_line_1_copy, 0, wx.EXPAND, 0)
        sizer_12.Add(self.label_8_copy_copy, 0, 0, 0)
        sizer_12.Add(self.gen_versiontxt, 0, 0, 0)
        sizer_11.Add(sizer_12, 0, wx.EXPAND, 0)
        sizer_11.Add(self.static_line_1_copy_2, 0, wx.EXPAND, 0)
        sizer_12_copy.Add(self.label_8_copy, 0, 0, 0)
        sizer_12_copy.Add(self.gen_modeltxt, 0, 0, 0)
        sizer_11.Add(sizer_12_copy, 0, wx.EXPAND, 0)
        sizer_11.Add(self.static_line_1_copy_3, 0, wx.EXPAND, 0)
        sizer_12_copy_1.Add(self.label_8_copy_1, 0, 0, 0)
        sizer_12_copy_1.Add(self.gen_IDtxt, 0, 0, 0)
        sizer_11.Add(sizer_12_copy_1, 0, wx.EXPAND, 0)
        sizer_11.Add(self.static_line_1_copy_4, 0, wx.EXPAND, 0)
        sizer_3.Add(sizer_11, 0, wx.EXPAND, 0)
        sizer_12_copy_1_copy.Add(self.label_8_copy_1_copy, 0, 0, 0)
        sizer_12_copy_1_copy.Add(self.startup_checkbox, 0, 0, 0)
        sizer_3.Add(sizer_12_copy_1_copy, 0, wx.EXPAND, 0)
        sizer_10.Add(sizer_3, 0, wx.EXPAND, 0)
        sizer_9.Add(sizer_10, 0, wx.EXPAND, 0)
        sizer_9.Add(self.static_line_1_copy_1, 0, wx.EXPAND, 0)
        sizer_2_copy.Add(sizer_9, 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_2_copy, 0, wx.EXPAND, 0)
        self.panel_1.SetSizer(sizer_2)
        sizer_1.Add(self.panel_1, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

# end of class Geninfo_config_frame

