#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Thu Feb  3 22:52:23 2011

import wx

# begin wxGlade: extracode
# end wxGlade
import os
path=os.getcwd()+'/States/TestState/start_box/'

class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_8 = wx.Panel(self, -1)
        self.bitmap_1 = wx.StaticBitmap(self.panel_8, -1, wx.Bitmap(path+"rxboxstartlogo.png", wx.BITMAP_TYPE_ANY))
        self.panel_3 = wx.Panel(self.panel_8, -1)
        self.label_1 = wx.StaticText(self.panel_8, -1, "Process: ")
        self.statlabel = wx.StaticText(self.panel_8, -1, "Initializing....................")
        self.panel_4 = wx.Panel(self.panel_8, -1)
        self.panel_10 = wx.Panel(self.panel_8, -1)
        self.panel_8_copy = wx.Panel(self.panel_8, -1)
        self.ecgbmp = wx.StaticBitmap(self.panel_8, -1, wx.Bitmap(path+"ecg_standby.png", wx.BITMAP_TYPE_ANY))
        self.panel_8_copy_copy = wx.Panel(self.panel_8, -1)
        self.spo2bmp = wx.StaticBitmap(self.panel_8, -1, wx.Bitmap(path+"spo2_standby.png", wx.BITMAP_TYPE_ANY))
        self.panel_8_copy_copy_copy = wx.Panel(self.panel_8, -1)
        self.bpbmp = wx.StaticBitmap(self.panel_8, -1, wx.Bitmap(path+"bp_standby.png", wx.BITMAP_TYPE_ANY))
        self.panel_8_copy_2 = wx.Panel(self.panel_8, -1)
        self.cambmp = wx.StaticBitmap(self.panel_8, -1, wx.Bitmap(path+"cam_standby.png", wx.BITMAP_TYPE_ANY))
        self.panel_8_copy_3 = wx.Panel(self.panel_8, -1)
        self.dcmbmp = wx.StaticBitmap(self.panel_8, -1, wx.Bitmap(path+"dcm_standby.png", wx.BITMAP_TYPE_ANY))
        self.panel_8_copy_4 = wx.Panel(self.panel_8, -1)
        self.edfbmp = wx.StaticBitmap(self.panel_8, -1, wx.Bitmap(path+"edf_standby.png", wx.BITMAP_TYPE_ANY))
        self.panel_8_copy_5 = wx.Panel(self.panel_8, -1)
        self.netbmp = wx.StaticBitmap(self.panel_8, -1, wx.Bitmap(path+"net_standby.png", wx.BITMAP_TYPE_ANY))
        self.panel_9 = wx.Panel(self.panel_8, -1)
        self.panel_7 = wx.Panel(self.panel_8, -1)
        self.details_btn = wx.Button(self.panel_8, -1, "<<Details>>", style=wx.BU_EXACTFIT)
        self.stat_txt = wx.TextCtrl(self.panel_8, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY|wx.HSCROLL)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.on_Details, self.details_btn)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame_1")
        self.SetSize((557, 537))
        self.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.panel_3.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.label_1.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.label_1.SetForegroundColour(wx.Colour(0, 0, 0))
        self.label_1.SetFont(wx.Font(7, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.statlabel.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.statlabel.SetFont(wx.Font(7, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.panel_4.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.panel_10.SetMinSize((557, 10))
        self.panel_10.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.panel_8_copy.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.panel_8_copy_copy.SetMinSize((20, 45))
        self.panel_8_copy_copy.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.panel_8_copy_copy_copy.SetMinSize((20, 45))
        self.panel_8_copy_copy_copy.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.panel_8_copy_2.SetMinSize((20, 45))
        self.panel_8_copy_2.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.panel_8_copy_3.SetMinSize((20, 45))
        self.panel_8_copy_3.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.panel_8_copy_4.SetMinSize((20, 45))
        self.panel_8_copy_4.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.panel_8_copy_5.SetMinSize((20, 45))
        self.panel_8_copy_5.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.panel_9.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.panel_7.SetMinSize((557, 8))
        self.panel_7.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.details_btn.SetMinSize((550, 20))
        self.details_btn.SetFont(wx.Font(6, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.stat_txt.SetMinSize((550, 120))
        self.panel_8.SetMinSize((557, 532))
        self.panel_8.SetBackgroundColour(wx.Colour(255, 255, 255))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self.bitmap_1, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_3.Add(self.panel_3, 0, wx.EXPAND, 0)
        sizer_3.Add(self.label_1, 0, 0, 0)
        sizer_3.Add(self.statlabel, 0, 0, 0)
        sizer_3.Add(self.panel_4, 0, wx.EXPAND, 0)
        sizer_2.Add(sizer_3, 0, wx.EXPAND, 0)
        sizer_2.Add(self.panel_10, 0, wx.EXPAND, 0)
        sizer_4.Add(self.panel_8_copy, 1, wx.EXPAND, 0)
        sizer_4.Add(self.ecgbmp, 0, 0, 0)
        sizer_4.Add(self.panel_8_copy_copy, 0, wx.EXPAND, 0)
        sizer_4.Add(self.spo2bmp, 0, 0, 0)
        sizer_4.Add(self.panel_8_copy_copy_copy, 0, wx.EXPAND, 0)
        sizer_4.Add(self.bpbmp, 0, 0, 0)
        sizer_4.Add(self.panel_8_copy_2, 0, wx.EXPAND, 0)
        sizer_4.Add(self.cambmp, 0, 0, 0)
        sizer_4.Add(self.panel_8_copy_3, 0, wx.EXPAND, 0)
        sizer_4.Add(self.dcmbmp, 0, 0, 0)
        sizer_4.Add(self.panel_8_copy_4, 0, wx.EXPAND, 0)
        sizer_4.Add(self.edfbmp, 0, 0, 0)
        sizer_4.Add(self.panel_8_copy_5, 0, wx.EXPAND, 0)
        sizer_4.Add(self.netbmp, 0, 0, 0)
        sizer_4.Add(self.panel_9, 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_4, 0, wx.EXPAND, 0)
        sizer_2.Add(self.panel_7, 0, wx.EXPAND, 0)
        sizer_5.Add(self.details_btn, 0, wx.ALIGN_BOTTOM|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_5.Add(self.stat_txt, 1, 0, 0)
        sizer_2.Add(sizer_5, 0, wx.EXPAND, 0)
        self.panel_8.SetSizer(sizer_2)
        sizer_1.Add(self.panel_8, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        self.Centre()
        # end wxGlade

    def on_Details(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `on_Details' not implemented"
        event.Skip()

# end of class MyFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
