#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Mon Aug  2 14:17:36 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class SnapFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SnapFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.video_panel = wx.Panel(self, -1)
        self.snap_button = wx.Button(self, -1, "Snap")
        self.static_line_1 = wx.StaticLine(self, -1)
        self.picture_panel = wx.Panel(self, -1)
        self.final_button = wx.Button(self, -1, "Finalize")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: SnapFrame.__set_properties
        self.SetTitle("RxBox Snapshot")
        self.video_panel.SetMinSize((400, 288))
        self.picture_panel.SetMinSize((176,144))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: SnapFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        video_sizer = wx.BoxSizer(wx.VERTICAL)
        video_sizer.Add(self.video_panel, 1, wx.ALL|wx.EXPAND, 0)
        video_sizer.Add(self.snap_button, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_2.Add(video_sizer, 1, wx.EXPAND, 0)
        sizer_2.Add(self.static_line_1, 0, wx.EXPAND, 0)
        sizer_3.Add(self.picture_panel, 1, wx.EXPAND, 0)
        sizer_3.Add(self.final_button, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_2.Add(sizer_3, 0, wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class SnapFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = SnapFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
