#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Tue Aug 31 14:22:10 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class SnapshotPanel2(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SnapshotPanel2.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.video_panel = wx.Panel(self, -1)
        self.panel_1 = wx.Panel(self, -1)
        self.snapbutton = wx.Button(self, -1, "Snapshot")
        self.panel_2 = wx.Panel(self, -1)
        self.deletebutton = wx.BitmapButton(self, -1, wx.Bitmap("Icons/trash_icon.jpeg", wx.BITMAP_TYPE_ANY))
        self.image_list = wx.ListCtrl(self, -1, style=wx.LC_ICON|wx.SUNKEN_BORDER)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnSnapshot, self.snapbutton)
        self.Bind(wx.EVT_BUTTON, self.OnDelete, self.deletebutton)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: SnapshotPanel2.__set_properties
        self.deletebutton.SetMinSize((25, 25))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: SnapshotPanel2.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(self.video_panel, 10, wx.EXPAND, 0)
        sizer_2.Add(self.panel_1, 0, 0, 0)
        sizer_2.Add(self.snapbutton, 1, wx.EXPAND, 0)
        sizer_2.Add(self.panel_2, 0, wx.EXPAND, 0)
        sizer_2.Add(self.deletebutton, 0, 0, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        sizer_1.Add(self.image_list, 3, wx.ALL|wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        # end wxGlade

    def OnSnapshot(self, event): # wxGlade: SnapshotPanel2.<event_handler>
        print "Event handler `OnSnapshot' not implemented!"
        event.Skip()

    def OnDelete(self, event): # wxGlade: SnapshotPanel2.<event_handler>
        print "Event handler `OnDelete' not implemented!"
        event.Skip()

# end of class SnapshotPanel2


