#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Thu Feb  4 11:41:25 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class ReferPanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ReferPanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.im_label_panel = wx.Panel(self, -1)
        self.video_label = wx.Panel(self, -1)
        self.Videoconf_Label = wx.StaticText(self.video_label, -1, "Video", style=wx.ALIGN_CENTRE)
        self.video_panel = wx.Panel(self, -1)
        self.IM_Label = wx.StaticText(self.im_label_panel, -1, "Instant Messaging", style=wx.ALIGN_CENTRE)
        self.IMtexts_Text = wx.TextCtrl(self, -1, "", style=wx.TE_PROCESS_ENTER|wx.TE_MULTILINE|wx.TE_READONLY)
        self.IMreply_Text = wx.TextCtrl(self, -1, "", style=wx.TE_PROCESS_ENTER|wx.TE_MULTILINE)
        self.im_bottom_panel = wx.Panel(self, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ReferPanel.__set_properties
        self.Videoconf_Label.SetMinSize((320, 19))
        self.Videoconf_Label.SetBackgroundColour(wx.Colour(251, 255, 100))
        self.Videoconf_Label.SetFont(wx.Font(10, wx.MODERN, wx.NORMAL, wx.BOLD, 0, "Arial"))
        self.video_label.SetBackgroundColour(wx.Colour(253, 255, 191))
        self.video_panel.SetMinSize((320,240))
        self.IM_Label.SetMinSize((320, 19))
        self.IM_Label.SetBackgroundColour(wx.Colour(253, 255, 191))
        self.IM_Label.SetFont(wx.Font(10, wx.MODERN, wx.NORMAL, wx.BOLD, 0, "Arial"))
        self.im_label_panel.SetBackgroundColour(wx.Colour(253, 255, 191))
        self.IMtexts_Text.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.IMreply_Text.SetBackgroundColour(wx.Colour(255, 255, 255))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ReferPanel.__do_layout
        refer_panel_sizer = wx.FlexGridSizer(3, 1, 0, 0)
        im_main_sizer = wx.BoxSizer(wx.VERTICAL)
        im_text_main_sizer = wx.BoxSizer(wx.HORIZONTAL)
        im_text_sizer = wx.BoxSizer(wx.VERTICAL)
        im_label_sizer = wx.BoxSizer(wx.VERTICAL)
        video_sizer = wx.BoxSizer(wx.VERTICAL)
        video_holder = wx.FlexGridSizer(2, 1, 0, 0)
        video_label_sizer = wx.BoxSizer(wx.VERTICAL)
        video_label_sizer.Add(self.Videoconf_Label, 1, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        self.video_label.SetSizer(video_label_sizer)
        video_sizer.Add(self.video_label, 0, wx.ALL|wx.EXPAND, 1)
        video_holder.Add(self.video_panel, 0, wx.ALL|wx.EXPAND, 0)
        video_sizer.Add(video_holder, 1, wx.EXPAND, 0)
        refer_panel_sizer.Add(video_sizer, 1, wx.ALL|wx.EXPAND, 1)
        im_label_sizer.Add(self.IM_Label, 1, wx.RIGHT|wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        self.im_label_panel.SetSizer(im_label_sizer)
        im_main_sizer.Add(self.im_label_panel, 0, wx.ALL|wx.EXPAND, 0)
        im_text_sizer.Add(self.IMtexts_Text, 8, wx.TOP|wx.EXPAND, 1)
        im_text_sizer.Add(self.IMreply_Text, 1, wx.TOP|wx.EXPAND, 0)
        im_text_sizer.Add(self.im_bottom_panel, 1, wx.EXPAND, 0)
        im_text_main_sizer.Add(im_text_sizer, 8, wx.EXPAND, 0)
        im_main_sizer.Add(im_text_main_sizer, 1, wx.EXPAND, 0)
        refer_panel_sizer.Add(im_main_sizer, 1, wx.EXPAND, 0)
        self.SetSizer(refer_panel_sizer)
        refer_panel_sizer.Fit(self)
        # end wxGlade

# end of class ReferPanel


