#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Mon Aug 23 20:16:14 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class BPPanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: BPPanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.bpNow_Button = wx.Button(self, -1, "BP NOW")
        self.setBPmaxpressure_combobox = wx.ComboBox(self, -1, choices=["140 mmHg", "160 mmHg", "180 mmHg", "200 mmHg", "220 mmHg", "240 mmHg"], style=wx.CB_DROPDOWN|wx.CB_DROPDOWN)
        self.bpbarpanel = wx.Panel(self, -1)
        self.bp_label = wx.StaticText(self, -1, "Blood Pressure", style=wx.ALIGN_CENTRE)
        self.bp_infolabel = wx.StaticText(self, -1, "--")
        self.bpvalue_label = wx.StaticText(self, -1, "-- / --", style=wx.ALIGN_CENTRE)
        self.bpunit_label = wx.StaticText(self, -1, "mmHg", style=wx.ALIGN_RIGHT)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.onBPNow, self.bpNow_Button)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: BPPanel.__set_properties
        self.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.bpNow_Button.SetBackgroundColour(wx.Colour(217, 217, 217))
        self.bpNow_Button.SetFont(wx.Font(12, wx.MODERN, wx.NORMAL, wx.BOLD, 0, ""))
        self.bpNow_Button.SetToolTipString("Acquire BP Reading")
        self.setBPmaxpressure_combobox.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.setBPmaxpressure_combobox.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.setBPmaxpressure_combobox.SetToolTipString("Set BP Acquisition Interval")
        self.setBPmaxpressure_combobox.SetSelection(2)
        self.bpbarpanel.SetMinSize((20,120))
        self.bpbarpanel.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.bp_label.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.bp_label.SetFont(wx.Font(9, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.bp_infolabel.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.bp_infolabel.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.bpvalue_label.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.bpvalue_label.SetFont(wx.Font(30, wx.MODERN, wx.NORMAL, wx.BOLD, 0, "Arial"))
        self.bpunit_label.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.bpunit_label.SetFont(wx.Font(10, wx.MODERN, wx.NORMAL, wx.BOLD, 0, "Arial"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: BPPanel.__do_layout
        bpnow_horizontal_sizer = wx.BoxSizer(wx.HORIZONTAL)
        bp_sizer = wx.BoxSizer(wx.VERTICAL)
        bplabelsizer = wx.BoxSizer(wx.HORIZONTAL)
        bp_label_sizer = wx.BoxSizer(wx.HORIZONTAL)
        nowButton_vertical_sizer = wx.BoxSizer(wx.VERTICAL)
        nowButton_vertical_sizer.Add(self.bpNow_Button, 2, wx.EXPAND, 0)
        nowButton_vertical_sizer.Add(self.setBPmaxpressure_combobox, 1, wx.EXPAND, 0)
        bpnow_horizontal_sizer.Add(nowButton_vertical_sizer, 1, wx.ALL|wx.EXPAND, 1)
        bpnow_horizontal_sizer.Add(self.bpbarpanel, 0, wx.ALL|wx.EXPAND, 0)
        bp_label_sizer.Add(self.bp_label, 2, wx.BOTTOM, 1)
        bp_label_sizer.Add(self.bp_infolabel, 3, wx.BOTTOM|wx.EXPAND, 1)
        bp_sizer.Add(bp_label_sizer, 0, wx.EXPAND, 0)
        bplabelsizer.Add(self.bpvalue_label, 1, wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        bp_sizer.Add(bplabelsizer, 1, wx.ALL|wx.EXPAND, 0)
        bp_sizer.Add(self.bpunit_label, 0, wx.ALIGN_RIGHT, 0)
        bpnow_horizontal_sizer.Add(bp_sizer, 3, wx.EXPAND, 0)
        self.SetSizer(bpnow_horizontal_sizer)
        bpnow_horizontal_sizer.Fit(self)
        # end wxGlade

    def onBPNow(self, event): # wxGlade: BPPanel.<event_handler>
        print "Event handler `onBPNow' not implemented!"
        event.Skip()

# end of class BPPanel


