#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Tue Aug 31 11:13:27 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class LogFilePanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: LogFilePanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.panel_2 = wx.Panel(self, -1)
        self.panel_1 = wx.Panel(self.panel_2, -1)
        self.bitmap_1 = wx.StaticBitmap(self.panel_2, -1, wx.Bitmap("Icons/support_icon.jpg", wx.BITMAP_TYPE_ANY))
        self.label_main = wx.StaticText(self.panel_2, -1, "Support")
        self.panel_2_copy = wx.Panel(self.panel_2, -1)
        self.static_line_1 = wx.StaticLine(self, -1)
        self.label_idlabel = wx.StaticText(self, -1, "Rxbox ID: ")
        self.label_id = wx.StaticText(self, -1, "")
        self.static_line_2 = wx.StaticLine(self, -1)
        self.label_1 = wx.StaticText(self, -1, "Comment:")
        self.text_ctrl_1 = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE|wx.TE_LINEWRAP|wx.TE_WORDWRAP)
        self.send = wx.Button(self, -1, "Send Log Files")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.sendlogfile, self.send)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: LogFilePanel.__set_properties
        self.SetBackgroundColour(wx.Colour(192, 192, 192))
        self.panel_1.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.bitmap_1.SetMinSize((64, 64))
        self.label_main.SetFont(wx.Font(20, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.panel_2_copy.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.panel_2.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.static_line_1.SetToolTipString("Send Log Files")
        self.label_idlabel.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: LogFilePanel.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(self.panel_1, 1, wx.EXPAND, 0)
        sizer_3.Add(self.bitmap_1, 0, wx.EXPAND, 0)
        sizer_3.Add(self.label_main, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_3.Add(self.panel_2_copy, 1, wx.EXPAND, 0)
        self.panel_2.SetSizer(sizer_3)
        sizer_1.Add(self.panel_2, 0, wx.EXPAND, 0)
        sizer_1.Add(self.static_line_1, 0, wx.EXPAND, 0)
        sizer_2.Add(self.label_idlabel, 0, 0, 0)
        sizer_2.Add(self.label_id, 0, 0, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        sizer_1.Add(self.static_line_2, 0, wx.EXPAND, 0)
        sizer_1.Add(self.label_1, 0, 0, 0)
        sizer_1.Add(self.text_ctrl_1, 6, wx.EXPAND, 0)
        sizer_1.Add(self.send, 1, wx.ALIGN_CENTER_HORIZONTAL, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        # end wxGlade

    def sendlogfile(self, event): # wxGlade: LogFilePanel.<event_handler>
        print "Event handler `sendlogfile' not implemented!"
        event.Skip()

# end of class LogFilePanel


