#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sun May  9 18:34:56 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class SnapshotPanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SnapshotPanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.snapshot_panel = wx.Panel(self, -1)
        self.prev_snapshot = wx.Button(self, -1, "<<")
        self.snapshot = wx.BitmapButton(self, -1, wx.Bitmap("Icons/snapshot_icon.png", wx.BITMAP_TYPE_ANY), style=wx.BU_AUTODRAW)
        self.next_snapshot = wx.Button(self, -1, ">>")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.onPrevSnapshot, self.prev_snapshot)
        self.Bind(wx.EVT_BUTTON, self.onSnapshot, self.snapshot)
        self.Bind(wx.EVT_BUTTON, self.onNextSnapshot, self.next_snapshot)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: SnapshotPanel.__set_properties
        self.snapshot_panel.SetMinSize((120,90))
        self.snapshot_panel.SetToolTipString("Displays Captured Image")
        self.prev_snapshot.SetMinSize((40,30))
        self.prev_snapshot.SetToolTipString("Show Previously Captured Images")
        self.snapshot.SetMinSize((40,30))
        self.snapshot.SetToolTipString("Acquire Snapshot")
        self.next_snapshot.SetMinSize((40,30))
        self.next_snapshot.SetToolTipString("Show Captured Images")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: SnapshotPanel.__do_layout
        snapshot_sizer = wx.FlexGridSizer(2, 1, 0, 0)
        snapshot_button_sizer = wx.FlexGridSizer(1, 3, 0, 0)
        snapshot_sizer.Add(self.snapshot_panel, 1, wx.EXPAND, 0)
        snapshot_button_sizer.Add(self.prev_snapshot, 1, wx.EXPAND, 0)
        snapshot_button_sizer.Add(self.snapshot, 1, wx.EXPAND, 0)
        snapshot_button_sizer.Add(self.next_snapshot, 1, wx.EXPAND, 0)
        snapshot_sizer.Add(snapshot_button_sizer, 1, wx.EXPAND, 0)
        self.SetSizer(snapshot_sizer)
        snapshot_sizer.Fit(self)
        # end wxGlade

    def onPrevSnapshot(self, event): # wxGlade: SnapshotPanel.<event_handler>
        print "Event handler `onPrevSnapshot' not implemented!"
        event.Skip()

    def onSnapshot(self, event): # wxGlade: SnapshotPanel.<event_handler>
        print "Event handler `onSnapshot' not implemented!"
        event.Skip()

    def onNextSnapshot(self, event): # wxGlade: SnapshotPanel.<event_handler>
        print "Event handler `onNextSnapshot' not implemented!"
        event.Skip()

# end of class SnapshotPanel


