#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Thu Jan 14 15:49:01 2010

#GUI imports
import wx
from ECG_Demo_GUI import *
from ecgplotter import Plotter
from lead12dialog import Lead12Dialog
from ecgplot import extendedPlotter

#sensor imports
import ECG

import time
from edf import *
import datetime
# begin wxGlade: extracode
# end wxGlade
        
        
DAQDUR = 3

class Lead12Dialog2(Lead12Dialog):
    """Creates the 12 Lead Dialog Window where the 12 leads will be plotted"""
    
    def __init__(self, ECGdata, edfbin, *args, **kwds):
        """ initializes the placement of the plotter to the 12 lead dialog window

        """
        
        Lead12Dialog.__init__(self, *args, **kwds)
        self.ECGdata = ECGdata
        
        sizersize = self.leadI_sizer.GetSize()
        bigsizer = self.leadII_sizer.GetSize()
        self.plotter_I = Plotter(self, (308, 162))
        self.plotter_II = Plotter(self, (308, 162))
        self.plotter_III = Plotter(self, (308, 162))
        self.plotter_aVR = Plotter(self, (308, 162))
        self.plotter_aVL = Plotter(self, (308, 162))
        self.plotter_aVF = Plotter(self, (308, 162))
        self.plotter_V1 = Plotter(self, (308, 162))
        self.plotter_V2 = Plotter(self, (308, 162))
        self.plotter_V3 = Plotter(self, (308, 162))
        self.plotter_V4 = Plotter(self, (308, 162))
        self.plotter_V5 = Plotter(self, (308, 162))
        self.plotter_V6 = Plotter(self, (308, 162))
        
        self.leadI_sizer.Add(self.plotter_I.plotpanel, 1, wx.LEFT | wx.RIGHT | wx.BOTTOM | wx.EXPAND, 4)
        self.small_leadII_sizer.Add(self.plotter_II.plotpanel, 1, wx.LEFT | wx.RIGHT | wx.BOTTOM | wx.EXPAND, 4)
        self.leadIII_sizer.Add(self.plotter_III.plotpanel, 1, wx.LEFT | wx.RIGHT | wx.BOTTOM | wx.EXPAND, 4)
        self.aVR_sizer.Add(self.plotter_aVR.plotpanel, 1, wx.LEFT | wx.RIGHT | wx.BOTTOM | wx.EXPAND, 4)
        self.aVL_sizer.Add(self.plotter_aVL.plotpanel, 1, wx.LEFT | wx.RIGHT | wx.BOTTOM | wx.EXPAND, 4)
        self.aVF_sizer.Add(self.plotter_aVF.plotpanel, 1, wx.LEFT | wx.RIGHT | wx.BOTTOM | wx.EXPAND, 4)
        self.V1_sizer.Add(self.plotter_V1.plotpanel, 1, wx.LEFT | wx.RIGHT | wx.BOTTOM | wx.EXPAND, 4)
        self.V2_sizer.Add(self.plotter_V2.plotpanel, 1, wx.LEFT | wx.RIGHT | wx.BOTTOM | wx.EXPAND, 4)
        self.V3_sizer.Add(self.plotter_V3.plotpanel, 1, wx.LEFT | wx.RIGHT | wx.BOTTOM | wx.EXPAND, 4)
        self.V4_sizer.Add(self.plotter_V4.plotpanel, 1, wx.LEFT | wx.RIGHT | wx.BOTTOM | wx.EXPAND, 4)
        self.V5_sizer.Add(self.plotter_V5.plotpanel, 1, wx.LEFT | wx.RIGHT | wx.BOTTOM | wx.EXPAND, 4)
        self.V6_sizer.Add(self.plotter_V6.plotpanel, 1, wx.LEFT | wx.RIGHT | wx.BOTTOM | wx.EXPAND, 4)

        self.plotter_I.plot(self.ECGdata.ecg_leadI)
        self.plotter_II.plot(self.ECGdata.ecg_leadII)
        self.plotter_III.plot(self.ECGdata.ecg_leadIII)
        self.plotter_aVR.plot(self.ECGdata.ecg_leadaVR)
        self.plotter_aVL.plot(self.ECGdata.ecg_leadaVL)
        self.plotter_aVF.plot(self.ECGdata.ecg_leadaVF)
        self.plotter_V1.plot(self.ECGdata.ecg_leadV1)
        self.plotter_V2.plot(self.ECGdata.ecg_leadV2)
        self.plotter_V3.plot(self.ECGdata.ecg_leadV3)
        self.plotter_V4.plot(self.ECGdata.ecg_leadV4)
        self.plotter_V5.plot(self.ECGdata.ecg_leadV5)
        self.plotter_V6.plot(self.ECGdata.ecg_leadV6)
        
        self.plotter_bigII = extendedPlotter(self, bigsizer, edfbin+self.ECGdata.ecg_leadII)
        self.leadII_sizer.Add(self.plotter_bigII, 1, wx.LEFT | wx.RIGHT | wx.BOTTOM | wx.EXPAND, 4)

class MyFrame2(MyFrame):
    def __init__(self, *args, **kwds):
        MyFrame.__init__(self, *args, **kwds)
        self.plotter = Plotter(self, (1120, 380))
        self.plotgraph_sizer.Add(self.plotter.plotpanel, 1, wx.LEFT | wx.RIGHT | wx.BOTTOM | wx.EXPAND, 4)
        self.Bind(wx.EVT_CLOSE, self.onClose)
        
        self.port = '/dev/ttyUSB0'
        self.ECGDemo = ECG.ECG(port=self.port)
        self.ECGDemo.device_ready()
        if self.ECGDemo.device_ready_counter:
            self.ECG_Demo_statusbar.SetStatusText('Device Detected')
        else:
            self.ECG_Demo_statusbar.SetStatusText('Device Not Detected')
        self.ECGDemo.stop()
        
        self.patient1 = Patient('1', 'Timothy', 'Cena', 'Ebido', 'Servan', \
                                            'Male', '09.27.89', '19')
        self.edfbin = [1.1]*1000+[-1.1]*1000+[0]*5500
        
        self.play_toggle = False
        self.timerStat = wx.Timer(self)
        self.timerPlot = wx.Timer(self)
        self.timerEDF = wx.Timer(self)
        self.Bind(wx.EVT_TIMER, self.statECG, self.timerStat)
        self.Bind(wx.EVT_TIMER, self.plotECG, self.timerPlot)
        self.Bind(wx.EVT_TIMER, self.make_edf, self.timerEDF)
        self.timerStat.Start(5000)
        self.timerEDF.Start(15000)
        self.plotter.plot(range(0,20)+[1]*1479+[1])

    def onClose(self, evt):
        """Displays a dialog prompt that asks the user to save data when user attempts to destroy the frame"""
        dlg = wx.MessageDialog(self, 'Are you sure you want to exit?', 'Exit', wx.YES_NO | wx.CANCEL)
        response = dlg.ShowModal()
        if response == wx.ID_CANCEL or response == wx.ID_NO:
            dlg.Destroy()
        else:
            dlg.Destroy()
            self.Destroy()   
            self.timerStat.Stop()
            self.timerEDF.Stop()
            self.timerPlot.Stop()
            self.ECGDemo.Stop_Thread()

    def make_edf(self, evt):
        if len(self.edfbin) >= 7500:    
            self.Endtime = datetime.datetime.today()
            self.Starttime = self.Endtime + datetime.timedelta(seconds= -15)
            self.strDate = self.Starttime.strftime("%d.%m.%y")
            self.strStarttime = self.Starttime.strftime("%H.%M.%S")
            self.strY2KDate = self.Starttime.strftime("%d-%b-%Y")
                    
            Biosignals = []
            temp = []
            for i in range(0,7500):
                temp.append(int(round(self.edfbin[i]/0.00263))+16383)
                
            Biosignal_ECG = BioSignal('II', 'CM', 'mV', -43, 43, 0, 32767, 'None', 7500, temp)
            Biosignals.append(Biosignal_ECG)
            
            del self.edfbin[0:7500]
            myedf = EDF(self.patient1, Biosignals, self.strDate, self.strStarttime, self.strY2KDate + \
                            ': LifeLink 15 second data of CorScience modules', \
                            1, 15)
            myedf.get(self.patient1)
            print 'EDF creation finished'
        else:
            print 'EDF have no enough data'
            print len(self.edfbin)
                
    def plotECG(self, evt):
        try:
            self.plotter.plot(self.ECGDemo.ecg_leadII[0:1500])
            temp = self.ECGDemo.Pop(end=125)
            for i in temp:
                self.edfbin.append(i)
            
        except:
            print 'No New Data'
            
    def statECG(self, evt):
        try:
            if self.ECGDemo.nodeR:
                self.R_bitmap.SetBitmap(wx.Bitmap("Icons/R_connected.png"))
            else:
                self.R_bitmap.SetBitmap(wx.Bitmap("Icons/R_unconnected.png"))
            if self.ECGDemo.nodeL:
                self.L_bitmap.SetBitmap(wx.Bitmap("Icons/L_connected.png"))
            else:
                self.L_bitmap.SetBitmap(wx.Bitmap("Icons/L_unconnected.png"))
            if self.ECGDemo.nodeN:
                self.N_bitmap.SetBitmap(wx.Bitmap("Icons/N_connected.png"))
            else:
                self.N_bitmap.SetBitmap(wx.Bitmap("Icons/N_unconnected.png"))
            if self.ECGDemo.nodeF:
                self.F_bitmap.SetBitmap(wx.Bitmap("Icons/F_connected.png"))
            else:
                self.F_bitmap.SetBitmap(wx.Bitmap("Icons/F_unconnected.png"))
            if self.ECGDemo.nodeC1:
                self.C1_bitmap.SetBitmap(wx.Bitmap("Icons/C1_connected.png"))
            else:
                self.C1_bitmap.SetBitmap(wx.Bitmap("Icons/C1_unconnected.png"))
            if self.ECGDemo.nodeC2:
                self.C2_bitmap.SetBitmap(wx.Bitmap("Icons/C2_connected.png"))
            else:
                self.C2_bitmap.SetBitmap(wx.Bitmap("Icons/C2_unconnected.png"))
            if self.ECGDemo.nodeC3:
                self.C3_bitmap.SetBitmap(wx.Bitmap("Icons/C3_connected.png"))
            else:
                self.C3_bitmap.SetBitmap(wx.Bitmap("Icons/C3_unconnected.png"))
            if self.ECGDemo.nodeC4:
                self.C4_bitmap.SetBitmap(wx.Bitmap("Icons/C4_connected.png"))
            else:
                self.C4_bitmap.SetBitmap(wx.Bitmap("Icons/C4_unconnected.png"))
            if self.ECGDemo.nodeC5:
                self.C5_bitmap.SetBitmap(wx.Bitmap("Icons/C5_connected.png"))
            else:
                self.C5_bitmap.SetBitmap(wx.Bitmap("Icons/C5_unconnected.png"))
            if self.ECGDemo.nodeC6:
                self.C6_bitmap.SetBitmap(wx.Bitmap("Icons/C6_connected.png"))
            else:
                self.C6_bitmap.SetBitmap(wx.Bitmap("Icons/C6_unconnected.png"))
        except:
            print 'No Lead Status Data'
        
    def play_button_clicked(self, event): # wxGlade: MyFrame.<event_handler>
        if self.play_toggle:
            self.play_toggle = False
            self.timerPlot.Stop()
            self.ECGDemo.Stop_Thread()
            print 'ECG Plot Stop'
        else:
            self.ECGDemo = ECG.ECG(port = '/dev/ttyUSB0',daqdur=DAQDUR)
            if self.ECGDemo.Start_Thread():
                self.play_toggle = True
                self.timerPlot.Start(250)
                self.edfbin = []
                print 'ECG Plot Start'
            

    def lead12_button_clicked(self, event): # wxGlade: MyFrame.<event_handler>
        if not self.play_toggle:
            self.play_toggle = True
            self.timerPlot.Start(250)
            self.edfbin = []
            self.ECGDemo = ECG.ECG(port = '/dev/ttyUSB0',daqdur=DAQDUR)
            self.ECGDemo.Start_Thread()
            time.sleep(6.1)
        self.ECGDemo.Stop_Thread()
        self.timerPlot.Stop()
        CreateDialog2 = Lead12Dialog2(self.ECGDemo,self.edfbin,self)
        CreateDialog2.ShowModal()
        self.timerPlot.Start(250)
        self.ECGDemo = ECG.ECG(port = '/dev/ttyUSB0',daqdur=DAQDUR)
        self.ECGDemo.Start_Thread()
        

# end of class MyFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    ECG_Demo = MyFrame2(None, -1, "")
    app.SetTopWindow(ECG_Demo)
    ECG_Demo.Show()
    app.MainLoop()
