#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Thu Jul 16 00:33:32 2009

import wx

# begin wxGlade: extracode
# end wxGlade



class Lead12Dialog(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Lead12Dialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.MAXIMIZE_BOX|wx.MINIMIZE_BOX
        wx.Frame.__init__(self, *args, **kwds)
        self.aVR_sizer_staticbox = wx.StaticBox(self, -1, "aVR")
        self.V1_sizer_staticbox = wx.StaticBox(self, -1, "V1")
        self.V4_sizer_staticbox = wx.StaticBox(self, -1, "V4")
        self.small_leadII_sizer_staticbox = wx.StaticBox(self, -1, "II")
        self.aVL_sizer_staticbox = wx.StaticBox(self, -1, "aVL")
        self.V2_sizer_staticbox = wx.StaticBox(self, -1, "V2")
        self.V5_sizer_staticbox = wx.StaticBox(self, -1, "V5")
        self.leadIII_sizer_staticbox = wx.StaticBox(self, -1, "III")
        self.aVF_sizer_staticbox = wx.StaticBox(self, -1, "aVF")
        self.V3_sizer_staticbox = wx.StaticBox(self, -1, "V3")
        self.V6_sizer_staticbox = wx.StaticBox(self, -1, "V6")
        self.leadII_sizer_staticbox = wx.StaticBox(self, -1, "II")
        self.leadI_sizer_staticbox = wx.StaticBox(self, -1, "I")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Lead12Dialog.__set_properties
        self.SetTitle("12 Lead ECG")
        self.SetSize((916, 710))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Lead12Dialog.__do_layout
        main_vertical_sizer = wx.BoxSizer(wx.VERTICAL)
        fourth_row_sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.leadII_sizer = wx.StaticBoxSizer(self.leadII_sizer_staticbox, wx.VERTICAL)
        third_row_sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.V6_sizer = wx.StaticBoxSizer(self.V6_sizer_staticbox, wx.VERTICAL)
        self.V3_sizer = wx.StaticBoxSizer(self.V3_sizer_staticbox, wx.VERTICAL)
        self.aVF_sizer = wx.StaticBoxSizer(self.aVF_sizer_staticbox, wx.VERTICAL)
        self.leadIII_sizer = wx.StaticBoxSizer(self.leadIII_sizer_staticbox, wx.VERTICAL)
        second_row_sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.V5_sizer = wx.StaticBoxSizer(self.V5_sizer_staticbox, wx.VERTICAL)
        self.V2_sizer = wx.StaticBoxSizer(self.V2_sizer_staticbox, wx.VERTICAL)
        self.aVL_sizer = wx.StaticBoxSizer(self.aVL_sizer_staticbox, wx.VERTICAL)
        self.small_leadII_sizer = wx.StaticBoxSizer(self.small_leadII_sizer_staticbox, wx.VERTICAL)
        first_row_sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.V4_sizer = wx.StaticBoxSizer(self.V4_sizer_staticbox, wx.VERTICAL)
        self.V1_sizer = wx.StaticBoxSizer(self.V1_sizer_staticbox, wx.VERTICAL)
        self.aVR_sizer = wx.StaticBoxSizer(self.aVR_sizer_staticbox, wx.VERTICAL)
        self.leadI_sizer = wx.StaticBoxSizer(self.leadI_sizer_staticbox, wx.VERTICAL)
        first_row_sizer.Add(self.leadI_sizer, 1, wx.EXPAND, 0)
        first_row_sizer.Add(self.aVR_sizer, 1, wx.EXPAND, 0)
        first_row_sizer.Add(self.V1_sizer, 1, wx.EXPAND, 0)
        first_row_sizer.Add(self.V4_sizer, 1, wx.EXPAND, 0)
        main_vertical_sizer.Add(first_row_sizer, 1, wx.EXPAND, 0)
        second_row_sizer.Add(self.small_leadII_sizer, 1, wx.EXPAND, 0)
        second_row_sizer.Add(self.aVL_sizer, 1, wx.EXPAND, 0)
        second_row_sizer.Add(self.V2_sizer, 1, wx.EXPAND, 0)
        second_row_sizer.Add(self.V5_sizer, 1, wx.EXPAND, 0)
        main_vertical_sizer.Add(second_row_sizer, 1, wx.EXPAND, 0)
        third_row_sizer.Add(self.leadIII_sizer, 1, wx.EXPAND, 0)
        third_row_sizer.Add(self.aVF_sizer, 1, wx.EXPAND, 0)
        third_row_sizer.Add(self.V3_sizer, 1, wx.EXPAND, 0)
        third_row_sizer.Add(self.V6_sizer, 1, wx.EXPAND, 0)
        main_vertical_sizer.Add(third_row_sizer, 1, wx.EXPAND, 0)
        fourth_row_sizer.Add(self.leadII_sizer, 1, wx.EXPAND, 0)
        main_vertical_sizer.Add(fourth_row_sizer, 1, wx.EXPAND, 0)
        self.SetSizer(main_vertical_sizer)
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class Lead12Dialog


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    dialog_1 = Lead12Dialog(None, -1, "")
    app.SetTopWindow(dialog_1)
    dialog_1.Show()
    app.MainLoop()
