##################################################
# file: DoctorLinkService_server.py
#
# skeleton generated by "ZSI.generate.wsdl2dispatch.ServiceModuleWriter"
#      /usr/local/bin/wsdl2py --complexType ws.xml
#
##################################################

from ZSI.schema import GED, GTD
from ZSI.TCcompound import ComplexType, Struct
from DoctorLinkService_types import *
from ZSI.ServiceContainer import ServiceSOAPBinding

# Messages  
push_msg = GED("http://web/", "push_msg").pyclass

push_msgResponse = GED("http://web/", "push_msgResponse").pyclass

msg_is_sent = GED("http://web/", "msg_is_sent").pyclass

msg_is_sentResponse = GED("http://web/", "msg_is_sentResponse").pyclass


# Service Skeletons
class DoctorLinkService(ServiceSOAPBinding):
    soapAction = {}
    root = {}

    def __init__(self, post='/TriageWS/DoctorLinkService', **kw):
        ServiceSOAPBinding.__init__(self, post)

    def soap_push_msg(self, ps, **kw):
        request = ps.Parse(push_msg.typecode)
        return request,push_msgResponse()

    soapAction[''] = 'soap_push_msg'
    root[(push_msg.typecode.nspname,push_msg.typecode.pname)] = 'soap_push_msg'

    def soap_msg_is_sent(self, ps, **kw):
        request = ps.Parse(msg_is_sent.typecode)
        return request,msg_is_sentResponse()

    soapAction[''] = 'soap_msg_is_sent'
    root[(msg_is_sent.typecode.nspname,msg_is_sent.typecode.pname)] = 'soap_msg_is_sent'

