#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sun Aug 29 20:45:18 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class Config_Gui(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Config_Gui.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_2 = wx.Panel(self, -1)
        self.tree = wx.TreeCtrl(self.panel_2, -1, style=wx.TR_HIDE_ROOT|wx.TR_HAS_BUTTONS)
        self.module = wx.Panel(self.panel_2, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Config_Gui.__set_properties
        self.SetTitle("frame_4")
        self.SetSize((600, 600))
        self.tree.SetMinSize((180, 600))
        self.module.SetMinSize((400, 600))
        self.panel_2.SetMinSize((600, 600))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Config_Gui.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(self.tree, 0, wx.EXPAND, 0)
        sizer_3.Add(self.module, 0, wx.EXPAND, 0)
        self.panel_2.SetSizer(sizer_3)
        sizer_2.Add(self.panel_2, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_2)
        self.Layout()
        # end wxGlade






