#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Mon Aug 23 19:28:38 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class CommPanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: CommPanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.StartStop_Button = wx.BitmapButton(self, -1, wx.Bitmap("Icons/PlayButton.png", wx.BITMAP_TYPE_ANY))
        self.StartStop_Label = wx.StaticText(self, -1, "Start")
        self.startstop_staticline = wx.StaticLine(self, -1, style=wx.LI_VERTICAL)
        self.Remark_Daq = wx.StaticText(self, -1, "       Remarks: ")
        self.RemarkValueDaq = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE)
        self.Send_Button = wx.BitmapButton(self, -1, wx.Bitmap("Icons/Send.png", wx.BITMAP_TYPE_ANY))
        self.Send_Label = wx.StaticText(self, -1, "Send")
        self.Call_Button = wx.BitmapButton(self, -1, wx.Bitmap("Icons/Refer.png", wx.BITMAP_TYPE_ANY))
        self.Call_Label = wx.StaticText(self, -1, "Call")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.onStartStop, self.StartStop_Button)
        self.Bind(wx.EVT_BUTTON, self.onSend, self.Send_Button)
        self.Bind(wx.EVT_BUTTON, self.onCall, self.Call_Button)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: CommPanel.__set_properties
        self.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.StartStop_Button.SetBackgroundColour(wx.Colour(50, 50, 204))
        self.StartStop_Button.SetToolTipString("Start data acquisition from the biomedical modules")
        self.StartStop_Button.SetSize(self.StartStop_Button.GetBestSize())
        self.StartStop_Label.SetFont(wx.Font(16, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, "Arial"))
        self.Remark_Daq.SetFont(wx.Font(16, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, "Arial"))
        self.RemarkValueDaq.SetMinSize((250, 54))
        self.Send_Button.SetToolTipString("Stop data acquisition from the biomedical modules")
        self.Send_Button.Enable(False)
        self.Send_Button.SetSize(self.Send_Button.GetBestSize())
        self.Send_Label.SetFont(wx.Font(16, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, "Arial"))
        self.Call_Button.SetToolTipString("Stop data acquisition from the biomedical modules")
        self.Call_Button.Enable(False)
        self.Call_Button.SetSize(self.Call_Button.GetBestSize())
        self.Call_Label.SetFont(wx.Font(16, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, "Arial"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: CommPanel.__do_layout
        buttons_sizer = wx.BoxSizer(wx.HORIZONTAL)
        buttons_sizer.Add(self.StartStop_Button, 0, wx.ALL, 4)
        buttons_sizer.Add(self.StartStop_Label, 0, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL, 4)
        buttons_sizer.Add(self.startstop_staticline, 0, wx.EXPAND, 0)
        buttons_sizer.Add(self.Remark_Daq, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        buttons_sizer.Add(self.RemarkValueDaq, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        buttons_sizer.Add((20, 20), 1, wx.ALL|wx.EXPAND, 0)
        buttons_sizer.Add(self.Send_Button, 0, wx.ALL, 4)
        buttons_sizer.Add(self.Send_Label, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        buttons_sizer.Add(self.Call_Button, 0, wx.ALL, 4)
        buttons_sizer.Add(self.Call_Label, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        self.SetSizer(buttons_sizer)
        buttons_sizer.Fit(self)
        # end wxGlade

    def onStartStop(self, event): # wxGlade: CommPanel.<event_handler>
        print "Event handler `onStartStop' not implemented!"
        event.Skip()

    def onSend(self, event): # wxGlade: CommPanel.<event_handler>
        print "Event handler `onSend' not implemented!"
        event.Skip()

    def onCall(self, event): # wxGlade: CommPanel.<event_handler>
        print "Event handler `onCall' not implemented!"
        event.Skip()

# end of class CommPanel


