#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Mon Aug 23 20:39:29 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class PatientInfoPanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: PatientInfoPanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.PatientInfoHeader_Label = wx.StaticText(self, -1, "Patient Information", style=wx.ALIGN_CENTRE|wx.ST_NO_AUTORESIZE)
        self.LastName = wx.StaticText(self, -1, "Name Last:  ")
        self.LastNameValue = wx.TextCtrl(self, -1, "")
        self.FirstName = wx.StaticText(self, -1, "   First:   ")
        self.FirstNameValue = wx.TextCtrl(self, -1, "")
        self.MiddleName = wx.StaticText(self, -1, "   Middle:   ")
        self.MiddleNameValue = wx.TextCtrl(self, -1, "")
        self.Address = wx.StaticText(self, -1, "Address:      ")
        self.AddressValue = wx.TextCtrl(self, -1, "")
        self.PhoneNumber = wx.StaticText(self, -1, "    Phone Number:   ")
        self.PhoneNumberValue = wx.TextCtrl(self, -1, "")
        self.Birthdate = wx.StaticText(self, -1, "Birthdate:    ")
        self.BirthMonth = wx.ComboBox(self, -1, choices=["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"], style=wx.CB_DROPDOWN|wx.CB_SIMPLE|wx.CB_DROPDOWN|wx.CB_READONLY)
        self.BirthDayCombo = wx.ComboBox(self, -1, choices=["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"], style=wx.CB_DROPDOWN|wx.CB_READONLY)
        self.BirthYear = wx.TextCtrl(self, -1, "")
        self.Age = wx.StaticText(self, -1, "    Age: ")
        self.AgeValue = wx.TextCtrl(self, -1, "")
        self.AgeCombo = wx.ComboBox(self, -1, choices=["Years", "Months", "Days"], style=wx.CB_DROPDOWN|wx.CB_DROPDOWN|wx.CB_READONLY)
        self.Gender = wx.StaticText(self, -1, "    Gender: ")
        self.GenderCombo = wx.ComboBox(self, -1, choices=["Male", "Female"], style=wx.CB_DROPDOWN|wx.CB_DROPDOWN|wx.CB_READONLY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: PatientInfoPanel.__set_properties
        self.SetSize((639, 104))
        self.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.PatientInfoHeader_Label.SetBackgroundColour(wx.Colour(219, 219, 112))
        self.PatientInfoHeader_Label.SetFont(wx.Font(10, wx.MODERN, wx.NORMAL, wx.BOLD, 0, "Arial"))
        self.LastNameValue.SetMinSize((135, 21))
        self.FirstNameValue.SetMinSize((135, 21))
        self.MiddleNameValue.SetMinSize((135, 21))
        self.AddressValue.SetMinSize((310, 21))
        self.PhoneNumberValue.SetMinSize((100, 21))
        self.BirthMonth.SetMinSize((110, 25))
        self.BirthMonth.SetSelection(0)
        self.BirthDayCombo.SetMinSize((55, 25))
        self.BirthDayCombo.SetSelection(-1)
        self.BirthYear.SetMinSize((50, 25))
        self.AgeValue.SetMinSize((30, 25))
        self.AgeCombo.SetMinSize((85, 25))
        self.AgeCombo.SetSelection(0)
        self.GenderCombo.SetMinSize((85, 25))
        self.GenderCombo.SetSelection(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: PatientInfoPanel.__do_layout
        patient_info_sizer = wx.BoxSizer(wx.VERTICAL)
        info_sizer = wx.BoxSizer(wx.HORIZONTAL)
        patient_row_sizer = wx.BoxSizer(wx.VERTICAL)
        patient_bottom_sizer = wx.BoxSizer(wx.HORIZONTAL)
        patient_middle_sizer = wx.BoxSizer(wx.HORIZONTAL)
        patient_top_sizer = wx.BoxSizer(wx.HORIZONTAL)
        patient_info_sizer.Add(self.PatientInfoHeader_Label, 0, wx.EXPAND, 0)
        patient_top_sizer.Add(self.LastName, 0, 0, 0)
        patient_top_sizer.Add(self.LastNameValue, 0, 0, 0)
        patient_top_sizer.Add(self.FirstName, 0, 0, 0)
        patient_top_sizer.Add(self.FirstNameValue, 0, 0, 0)
        patient_top_sizer.Add(self.MiddleName, 0, 0, 0)
        patient_top_sizer.Add(self.MiddleNameValue, 0, 0, 0)
        patient_row_sizer.Add(patient_top_sizer, 1, wx.EXPAND, 0)
        patient_middle_sizer.Add(self.Address, 0, 0, 0)
        patient_middle_sizer.Add(self.AddressValue, 0, 0, 0)
        patient_middle_sizer.Add(self.PhoneNumber, 0, 0, 0)
        patient_middle_sizer.Add(self.PhoneNumberValue, 0, 0, 0)
        patient_row_sizer.Add(patient_middle_sizer, 1, wx.EXPAND, 0)
        patient_bottom_sizer.Add(self.Birthdate, 0, 0, 0)
        patient_bottom_sizer.Add(self.BirthMonth, 0, 0, 0)
        patient_bottom_sizer.Add(self.BirthDayCombo, 0, 0, 0)
        patient_bottom_sizer.Add(self.BirthYear, 0, 0, 0)
        patient_bottom_sizer.Add(self.Age, 0, 0, 0)
        patient_bottom_sizer.Add(self.AgeValue, 0, 0, 0)
        patient_bottom_sizer.Add(self.AgeCombo, 0, 0, 0)
        patient_bottom_sizer.Add(self.Gender, 0, 0, 0)
        patient_bottom_sizer.Add(self.GenderCombo, 0, 0, 0)
        patient_row_sizer.Add(patient_bottom_sizer, 1, wx.EXPAND, 0)
        info_sizer.Add(patient_row_sizer, 1, wx.EXPAND, 0)
        patient_info_sizer.Add(info_sizer, 0, wx.EXPAND, 0)
        self.SetSizer(patient_info_sizer)
        # end wxGlade

# end of class PatientInfoPanel


