#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Wed Feb 17 20:23:04 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class Splash(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Splash.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.bitmap_1 = wx.StaticBitmap(self, -1, wx.Bitmap("/home/tim/Desktop/Caduceus_Logo_v2.jpg", wx.BITMAP_TYPE_ANY))
        self.text_ctrl_1 = wx.TextCtrl(self, -1, "Welcome to RxBox :)\nVersion 0.3426\n\nDeveloped by Tim & Thom", style=wx.TE_MULTILINE|wx.TE_READONLY)
        self.panel_1 = wx.Panel(self, -1)
        self.Back = wx.Button(self, -1, "<< Back")
        self.Next = wx.Button(self, -1, "Next >>")
        self.Skip = wx.Button(self, -1, "Skip")
        self.gauge = wx.Panel(self, -1)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.on_skip, self.Skip)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Splash.__set_properties
        self.SetTitle("dialog_1")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Splash.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self.bitmap_1, 0, 0, 0)
        sizer_2.Add(self.text_ctrl_1, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 4, wx.EXPAND, 0)
        sizer_3.Add(self.panel_1, 1, wx.EXPAND, 0)
        sizer_4.Add(self.Back, 0, 0, 0)
        sizer_4.Add(self.Next, 0, 0, 0)
        sizer_4.Add(self.Skip, 0, 0, 0)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_1.Add(self.gauge, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def on_skip(self, event): # wxGlade: Splash.<event_handler>
        print "Event handler `on_skip' not implemented!"
        event.Skip()

# end of class Splash


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    Splash_dialog = Splash(None, -1, "")
    app.SetTopWindow(Splash_dialog)
    Splash_dialog.Show()
    app.MainLoop()
