#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Tue Aug 31 12:59:22 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class SnapshotPanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SnapshotPanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.panel_5 = wx.Panel(self, -1)
        self.panel_6 = wx.Panel(self, -1)
        self.image_list = wx.ListCtrl(self, -1)
        self.static_line_1 = wx.StaticLine(self, -1, style=wx.LI_VERTICAL)
        self.panel_1 = wx.Panel(self, -1)
        self.snapshot = wx.BitmapButton(self, -1, wx.Bitmap("Icons/snapshot_icon.png", wx.BITMAP_TYPE_ANY), style=wx.BU_AUTODRAW)
        self.panel_2 = wx.Panel(self, -1)
        self.panel_3 = wx.Panel(self, -1)
        self.load = wx.BitmapButton(self, -1, wx.Bitmap("Icons/load_icon.jpeg", wx.BITMAP_TYPE_ANY), style=wx.BU_AUTODRAW)
        self.delete = wx.BitmapButton(self, -1, wx.Bitmap("Icons/trash_icon.jpeg", wx.BITMAP_TYPE_ANY), style=wx.BU_AUTODRAW)
        self.panel_4 = wx.Panel(self, -1)
        self.panel_9 = wx.Panel(self, -1)
        self.remove = wx.BitmapButton(self, -1, wx.Bitmap("Icons/remove_icon.jpeg", wx.BITMAP_TYPE_ANY), style=wx.BU_AUTODRAW)
        self.removeall = wx.BitmapButton(self, -1, wx.Bitmap("Icons/removeall_icon.jpeg", wx.BITMAP_TYPE_ANY), style=wx.BU_AUTODRAW)
        self.panel_10 = wx.Panel(self, -1)
        self.panel_8 = wx.Panel(self, -1)
        self.panel_7 = wx.Panel(self, -1)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.onSnapshot, self.snapshot)
        self.Bind(wx.EVT_BUTTON, self.OnLoad, self.load)
        self.Bind(wx.EVT_BUTTON, self.OnDelete, self.delete)
        self.Bind(wx.EVT_BUTTON, self.OnRemove, self.remove)
        self.Bind(wx.EVT_BUTTON, self.OnRemoveAll, self.removeall)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: SnapshotPanel.__set_properties
        self.SetSize((509, 298))
        self.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.panel_5.SetMinSize((5, 3))
        self.panel_5.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.panel_6.SetMinSize((3, 7))
        self.panel_6.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.panel_1.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.snapshot.SetMinSize((40, 30))
        self.snapshot.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.snapshot.SetForegroundColour(wx.Colour(255, 255, 255))
        self.snapshot.SetToolTipString("Acquire Snapshot")
        self.panel_2.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.panel_3.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.load.SetMinSize((12, 12))
        self.load.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.load.SetForegroundColour(wx.Colour(255, 255, 255))
        self.delete.SetMinSize((12, 12))
        self.delete.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.delete.SetForegroundColour(wx.Colour(255, 255, 255))
        self.panel_4.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.panel_9.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.remove.SetMinSize((12, 12))
        self.remove.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.remove.SetForegroundColour(wx.Colour(255, 255, 255))
        self.removeall.SetMinSize((12, 12))
        self.removeall.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.removeall.SetForegroundColour(wx.Colour(255, 255, 255))
        self.panel_10.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.panel_8.SetMinSize((3, 1))
        self.panel_8.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.panel_7.SetMinSize((1, 3))
        self.panel_7.SetBackgroundColour(wx.Colour(226, 255, 180))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: SnapshotPanel.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        snapshot_sizer3 = wx.BoxSizer(wx.VERTICAL)
        snapshot_sizer2 = wx.BoxSizer(wx.VERTICAL)
        snapshot_sizer1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(self.panel_5, 0, 0, 0)
        sizer_1.Add(self.panel_6, 0, 0, 0)
        sizer_1.Add(self.image_list, 10, wx.EXPAND, 0)
        sizer_1.Add(self.static_line_1, 0, wx.EXPAND, 0)
        snapshot_sizer1.Add(self.panel_1, 0, wx.ALL|wx.EXPAND, 0)
        snapshot_sizer1.Add(self.snapshot, 4, wx.ALL|wx.EXPAND, 0)
        snapshot_sizer1.Add(self.panel_2, 1, wx.ALL|wx.EXPAND, 0)
        sizer_1.Add(snapshot_sizer1, 2, wx.EXPAND, 0)
        snapshot_sizer2.Add(self.panel_3, 0, wx.ALL|wx.EXPAND, 0)
        snapshot_sizer2.Add(self.load, 2, wx.ALL|wx.EXPAND, 0)
        snapshot_sizer2.Add(self.delete, 2, wx.ALL|wx.EXPAND, 0)
        snapshot_sizer2.Add(self.panel_4, 1, wx.ALL|wx.EXPAND, 0)
        sizer_1.Add(snapshot_sizer2, 1, wx.EXPAND, 0)
        snapshot_sizer3.Add(self.panel_9, 0, wx.ALL|wx.EXPAND, 0)
        snapshot_sizer3.Add(self.remove, 2, wx.ALL|wx.EXPAND, 0)
        snapshot_sizer3.Add(self.removeall, 2, wx.ALL|wx.EXPAND, 0)
        snapshot_sizer3.Add(self.panel_10, 1, wx.ALL|wx.EXPAND, 0)
        sizer_1.Add(snapshot_sizer3, 1, wx.EXPAND, 0)
        sizer_1.Add(self.panel_8, 0, 0, 0)
        sizer_2.Add(sizer_1, 8, wx.EXPAND, 0)
        sizer_2.Add(self.panel_7, 0, 0, 0)
        self.SetSizer(sizer_2)
        # end wxGlade

    def onSnapshot(self, event): # wxGlade: SnapshotPanel.<event_handler>
        print "Event handler `onSnapshot' not implemented!"
        event.Skip()

    def OnLoad(self, event): # wxGlade: SnapshotPanel.<event_handler>
        print "Event handler `OnLoad' not implemented!"
        event.Skip()

    def OnDelete(self, event): # wxGlade: SnapshotPanel.<event_handler>
        print "Event handler `OnDelete' not implemented!"
        event.Skip()

    def OnRemove(self, event): # wxGlade: SnapshotPanel.<event_handler>
        print "Event handler `OnRemove' not implemented!"
        event.Skip()

    def OnRemoveAll(self, event): # wxGlade: SnapshotPanel.<event_handler>
        print "Event handler `OnRemoveAll' not implemented!"
        event.Skip()

# end of class SnapshotPanel


