#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Mon Aug 23 20:09:08 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class StethPanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: StethPanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.Stethoscope_Label = wx.StaticText(self, -1, "Stethoscope", style=wx.ALIGN_CENTRE|wx.ST_NO_AUTORESIZE)
        self.record_button = wx.BitmapButton(self, -1, wx.Bitmap("Icons/button_record.png", wx.BITMAP_TYPE_ANY))
        self.play_button = wx.BitmapButton(self, -1, wx.Bitmap("Icons/button_play.png", wx.BITMAP_TYPE_ANY))
        self.stop_button = wx.BitmapButton(self, -1, wx.Bitmap("Icons/button_stop.png", wx.BITMAP_TYPE_ANY))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.on_steth_record, self.record_button)
        self.Bind(wx.EVT_BUTTON, self.on_steth_play, self.play_button)
        self.Bind(wx.EVT_BUTTON, self.on_steth_stop, self.stop_button)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: StethPanel.__set_properties
        self.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.Stethoscope_Label.SetMinSize((165,40))
        self.Stethoscope_Label.SetBackgroundColour(wx.Colour(219, 219, 112))
        self.Stethoscope_Label.SetFont(wx.Font(10, wx.MODERN, wx.NORMAL, wx.BOLD, 0, "Arial"))
        self.record_button.SetToolTipString("Record Sounds")
        self.record_button.SetSize(self.record_button.GetBestSize())
        self.play_button.SetToolTipString("Play Recorded Sound")
        self.play_button.SetSize(self.play_button.GetBestSize())
        self.stop_button.SetToolTipString("Stop Play / Record")
        self.stop_button.SetSize(self.stop_button.GetBestSize())
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: StethPanel.__do_layout
        steth_sizer1 = wx.BoxSizer(wx.HORIZONTAL)
        steth_sizer = wx.BoxSizer(wx.VERTICAL)
        steth_button_sizer = wx.BoxSizer(wx.HORIZONTAL)
        steth_sizer.Add(self.Stethoscope_Label, 0, wx.EXPAND, 0)
        steth_button_sizer.Add(self.record_button, 0, 0, 0)
        steth_button_sizer.Add(self.play_button, 0, 0, 0)
        steth_button_sizer.Add(self.stop_button, 0, 0, 0)
        steth_sizer.Add(steth_button_sizer, 1, wx.EXPAND, 0)
        steth_sizer1.Add(steth_sizer, 1, wx.EXPAND, 0)
        self.SetSizer(steth_sizer1)
        steth_sizer1.Fit(self)
        # end wxGlade

    def on_steth_record(self, event): # wxGlade: StethPanel.<event_handler>
        print "Event handler `on_steth_record' not implemented!"
        event.Skip()

    def on_steth_play(self, event): # wxGlade: StethPanel.<event_handler>
        print "Event handler `on_steth_play' not implemented!"
        event.Skip()

    def on_steth_stop(self, event): # wxGlade: StethPanel.<event_handler>
        print "Event handler `on_steth_stop' not implemented!"
        event.Skip()

# end of class StethPanel


