#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Sat Jul 04 23:04:52 2009

import wx

# begin wxGlade: extracode
# end wxGlade



class RxFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: RxFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.RxFrame_StatusBar = self.CreateStatusBar(1, 0)
        self.PatientInfoHeader_Label = wx.StaticText(self, -1, "Patient Information", style=wx.ALIGN_CENTRE)
        self.PatientInfo_Label = wx.StaticText(self, -1, "No Information")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: RxFrame.__set_properties
        self.SetTitle("RxBox - Philippine General Hospital")
        self.SetSize((1285, 773))
        self.SetBackgroundColour(wx.Colour(245, 255, 207))
        self.RxFrame_StatusBar.SetStatusWidths([-1])
        # statusbar fields
        RxFrame_StatusBar_fields = ["RxBox ready..."]
        for i in range(len(RxFrame_StatusBar_fields)):
            self.RxFrame_StatusBar.SetStatusText(RxFrame_StatusBar_fields[i], i)
        self.PatientInfoHeader_Label.SetMinSize((620, 20))
        self.PatientInfoHeader_Label.SetBackgroundColour(wx.Colour(219, 219, 112))
        self.PatientInfoHeader_Label.SetFont(wx.Font(10, wx.MODERN, wx.NORMAL, wx.BOLD, 0, "Arial"))
        self.PatientInfo_Label.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.PatientInfo_Label.SetFont(wx.Font(10, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: RxFrame.__do_layout
        mainvertical_sizer = wx.BoxSizer(wx.VERTICAL)
        self.mainhorizontal_sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.info_daq_sizer = wx.BoxSizer(wx.VERTICAL)
        patient_info_tab_sizer = wx.BoxSizer(wx.HORIZONTAL)
        patient_info_sizer = wx.BoxSizer(wx.VERTICAL)
        info_sizer = wx.BoxSizer(wx.HORIZONTAL)
        patient_info_sizer.Add(self.PatientInfoHeader_Label, 1, wx.EXPAND, 0)
        info_sizer.Add(self.PatientInfo_Label, 3, wx.TOP|wx.EXPAND, 1)
        patient_info_sizer.Add(info_sizer, 4, wx.EXPAND, 0)
        patient_info_tab_sizer.Add(patient_info_sizer, 1, wx.EXPAND, 0)
        self.info_daq_sizer.Add(patient_info_tab_sizer, 0, wx.ALL|wx.EXPAND, 4)
        self.mainhorizontal_sizer.Add(self.info_daq_sizer, 2, wx.EXPAND, 0)
        mainvertical_sizer.Add(self.mainhorizontal_sizer, 1, wx.EXPAND, 0)
        self.SetSizer(mainvertical_sizer)
        self.Layout()
        self.SetSize((1285, 773))
        # end wxGlade

# end of class RxFrame

class DAQPanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: DAQPanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.button_window_separator = wx.StaticLine(self, -1)
        self.StartStop_Button = wx.BitmapButton(self, -1, wx.Bitmap("Icons/PlayButton.png", wx.BITMAP_TYPE_ANY))
        self.StartStop_Label = wx.StaticText(self, -1, "Start")
        self.Upload_Button = wx.BitmapButton(self, -1, wx.Bitmap("Icons/Upload.png", wx.BITMAP_TYPE_ANY))
        self.Upload_Label = wx.StaticText(self, -1, "Upload")
        self.Call_Button = wx.BitmapButton(self, -1, wx.Bitmap("Icons/Refer.png", wx.BITMAP_TYPE_ANY))
        self.Call_Label = wx.StaticText(self, -1, "Call")
        self.button_display_separator = wx.StaticLine(self, -1)
        self.nodeplacement_Bitmap = wx.StaticBitmap(self, -1, wx.Bitmap("Icons/NodePlacement.png", wx.BITMAP_TYPE_ANY), style=wx.SIMPLE_BORDER)
        self.calibsignal_Bitmap = wx.StaticBitmap(self, -1, wx.Bitmap("Icons/CalibrationSignal.png", wx.BITMAP_TYPE_ANY), style=wx.SIMPLE_BORDER)
        self.lead12_button = wx.Button(self, -1, "12 Lead")
        self.ecg_label = wx.StaticText(self, -1, "ECG WAVEFORM", style=wx.ALIGN_CENTRE)
        self.ecg_lowerdata_separator = wx.StaticLine(self, -1)
        self.bpNow_Button = wx.Button(self, -1, "NOW")
        self.setBPmins_combobox = wx.ComboBox(self, -1, choices=["5 min", "15 min", "30 min", "60 min"], style=wx.CB_DROPDOWN|wx.CB_DROPDOWN)
        self.bp_pressure = wx.Panel(self,-1)
        self.bp_pressure_indicator = wx.Gauge(self.bp_pressure,-1, 250, size=(20, 105),style=wx.GA_VERTICAL)
        self.bp_label = wx.StaticText(self, -1, "Blood Pressure", style=wx.ALIGN_CENTRE)
        self.bp_infolabel = wx.StaticText(self, -1, "--")
        self.bpvalue_label = wx.StaticText(self, -1, "-- / --", style=wx.ALIGN_CENTRE)
        self.panel_1 = wx.Panel(self, -1)
        self.bpunit_label = wx.StaticText(self, -1, "mmHg", style=wx.ALIGN_RIGHT)
        self.heartrate_label = wx.StaticText(self, -1, "Heart Rate", style=wx.ALIGN_CENTRE)
        self.heartrate_infolabel = wx.StaticText(self, -1, "--")
        self.bpmvalue_label = wx.StaticText(self, -1, "--", style=wx.ALIGN_CENTRE)
        self.panel_2 = wx.Panel(self, -1)
        self.bpmunit_label = wx.StaticText(self, -1, "bpm", style=wx.ALIGN_RIGHT)
        self.spo2_label = wx.StaticText(self, -1, "Blood Oxygen\nSaturation", style=wx.ALIGN_CENTRE)
        self.spo2_infolabel = wx.StaticText(self, -1, "--")
        self.spo2value_label = wx.StaticText(self, -1, "--", style=wx.ALIGN_CENTRE)
        self.panel_3 = wx.Panel(self, -1)
        self.spo2unit_label = wx.StaticText(self, -1, "%SpO2", style=wx.ALIGN_RIGHT)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.onStartStop, self.StartStop_Button)
        self.Bind(wx.EVT_BUTTON, self.onUpload, self.Upload_Button)
        self.Bind(wx.EVT_BUTTON, self.onCall, self.Call_Button)
        self.Bind(wx.EVT_BUTTON, self.on12Lead, self.lead12_button)
        self.Bind(wx.EVT_BUTTON, self.onBPNow, self.bpNow_Button)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: DAQPanel.__set_properties
        self.StartStop_Button.SetBackgroundColour(wx.Colour(50, 50, 204))
        self.StartStop_Button.SetToolTipString("Start data acquisition from the biomedical modules")
        self.StartStop_Button.SetSize(self.StartStop_Button.GetBestSize())
        self.StartStop_Label.SetFont(wx.Font(16, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, "Arial"))
        self.Upload_Button.SetToolTipString("Stop data acquisition from the biomedical modules")
        self.Upload_Button.Enable(False)
        self.Upload_Button.SetSize(self.Upload_Button.GetBestSize())
        self.Upload_Label.SetFont(wx.Font(16, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, "Arial"))
        self.Call_Button.SetToolTipString("Stop data acquisition from the biomedical modules")
        self.Call_Button.Enable(False)
        self.Call_Button.SetSize(self.Call_Button.GetBestSize())
        self.Call_Label.SetFont(wx.Font(16, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, "Arial"))
        self.button_display_separator.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.lead12_button.SetFont(wx.Font(16, wx.MODERN, wx.NORMAL, wx.BOLD, 0, ""))
        self.lead12_button.Enable(False)
        self.ecg_label.SetMinSize((306, 20))
        self.ecg_label.SetBackgroundColour(wx.Colour(241, 123, 241))
        self.ecg_label.SetFont(wx.Font(10, wx.MODERN, wx.NORMAL, wx.BOLD, 0, "Arial"))
        self.bpNow_Button.SetMinSize((50,70))
        self.bpNow_Button.SetFont(wx.Font(12, wx.MODERN, wx.NORMAL, wx.BOLD, 0, ""))
        self.setBPmins_combobox.SetSelection(0)
        self.bp_label.SetMinSize((60, 30))
        self.bp_label.SetBackgroundColour(wx.Colour(255, 217, 222))
        self.bp_label.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.bp_infolabel.SetMinSize((145, 30))
        self.bp_infolabel.SetBackgroundColour(wx.Colour(255, 217, 222))
        self.bp_infolabel.SetFont(wx.Font(9, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.bpvalue_label.SetMinSize((60, 40))
        self.bpvalue_label.SetBackgroundColour(wx.Colour(255, 217, 222))
        self.bpvalue_label.SetFont(wx.Font(30, wx.MODERN, wx.NORMAL, wx.BOLD, 0, "Arial"))
        self.panel_1.SetBackgroundColour(wx.Colour(255, 217, 222))
        self.bpunit_label.SetMinSize((60, 30))
        self.bpunit_label.SetBackgroundColour(wx.Colour(255, 217, 222))
        self.bpunit_label.SetFont(wx.Font(10, wx.MODERN, wx.NORMAL, wx.BOLD, 0, "Arial"))
        self.heartrate_label.SetMinSize((60, 30))
        self.heartrate_label.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.heartrate_label.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.heartrate_infolabel.SetMinSize((145, 30))
        self.heartrate_infolabel.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.heartrate_infolabel.SetFont(wx.Font(9, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.bpmvalue_label.SetMinSize((60, 40))
        self.bpmvalue_label.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.bpmvalue_label.SetFont(wx.Font(30, wx.MODERN, wx.NORMAL, wx.BOLD, 0, "Arial"))
        self.panel_2.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.bpmunit_label.SetMinSize((60, 30))
        self.bpmunit_label.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.bpmunit_label.SetFont(wx.Font(10, wx.MODERN, wx.NORMAL, wx.BOLD, 0, "Arial"))
        self.spo2_label.SetMinSize((60, 30))
        self.spo2_label.SetBackgroundColour(wx.Colour(201, 248, 255))
        self.spo2_label.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.spo2_infolabel.SetMinSize((145, 30))
        self.spo2_infolabel.SetBackgroundColour(wx.Colour(201, 248, 255))
        self.spo2_infolabel.SetFont(wx.Font(9, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.spo2value_label.SetMinSize((60, 40))
        self.spo2value_label.SetBackgroundColour(wx.Colour(201, 248, 255))
        self.spo2value_label.SetFont(wx.Font(30, wx.MODERN, wx.NORMAL, wx.BOLD, 0, "Arial"))
        self.panel_3.SetBackgroundColour(wx.Colour(201, 248, 255))
        self.spo2unit_label.SetMinSize((60, 30))
        self.spo2unit_label.SetBackgroundColour(wx.Colour(201, 248, 255))
        self.spo2unit_label.SetFont(wx.Font(10, wx.MODERN, wx.NORMAL, wx.BOLD, 0, "Arial"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: DAQPanel.__do_layout
        main_vertical_sizer = wx.BoxSizer(wx.VERTICAL)
        lowerdata_horizontal_sizer = wx.BoxSizer(wx.HORIZONTAL)
        spo2_sizer = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        spo2_label_sizer = wx.BoxSizer(wx.HORIZONTAL)
        heartrate_sizer = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        heartrate_label_sizer = wx.BoxSizer(wx.HORIZONTAL)
        nowButton_horizontal_sizer = wx.BoxSizer(wx.HORIZONTAL)
        bp_sizer = wx.BoxSizer(wx.VERTICAL)
        bp_grid = wx.FlexGridSizer(1, 2, 0, 0)
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        bp_label_sizer = wx.BoxSizer(wx.HORIZONTAL)
        nowButton_vertical_sizer = wx.BoxSizer(wx.VERTICAL)
        ecg_horizontal_sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.ecg_vertical_sizer = wx.BoxSizer(wx.VERTICAL)
        image_vertical_sizer = wx.BoxSizer(wx.VERTICAL)
        lead12_vertical_sizer = wx.BoxSizer(wx.VERTICAL)
        buttons_sizer = wx.BoxSizer(wx.HORIZONTAL)
        main_vertical_sizer.Add(self.button_window_separator, 0, wx.EXPAND, 0)
        buttons_sizer.Add(self.StartStop_Button, 0, wx.ALL, 4)
        buttons_sizer.Add(self.StartStop_Label, 0, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL, 4)
        buttons_sizer.Add((20, 20), 1, wx.ALL|wx.EXPAND, 4)
        buttons_sizer.Add(self.Upload_Button, 0, wx.ALL, 4)
        buttons_sizer.Add(self.Upload_Label, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        buttons_sizer.Add(self.Call_Button, 0, wx.ALL, 4)
        buttons_sizer.Add(self.Call_Label, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        main_vertical_sizer.Add(buttons_sizer, 0, wx.ALL|wx.EXPAND, 0)
        main_vertical_sizer.Add(self.button_display_separator, 0, wx.ALL|wx.EXPAND, 2)
        image_vertical_sizer.Add(self.nodeplacement_Bitmap, 0, wx.ALL|wx.EXPAND, 4)
        image_vertical_sizer.Add(self.calibsignal_Bitmap, 1, wx.ALL|wx.EXPAND, 4)
        lead12_vertical_sizer.Add(self.lead12_button, 1, wx.EXPAND, 0)
        lead12_vertical_sizer.Add((20, 50), 0, wx.EXPAND, 0)
        lead12_vertical_sizer.Add((20, 50), 0, wx.EXPAND, 0)
        image_vertical_sizer.Add(lead12_vertical_sizer, 1, wx.EXPAND, 0)
        ecg_horizontal_sizer.Add(image_vertical_sizer, 0, 0, 0)
        self.ecg_vertical_sizer.Add(self.ecg_label, 0, wx.ALL|wx.EXPAND, 4)
        ecg_horizontal_sizer.Add(self.ecg_vertical_sizer, 5, wx.EXPAND, 0)
        main_vertical_sizer.Add(ecg_horizontal_sizer, 1, wx.EXPAND, 0)
        main_vertical_sizer.Add(self.ecg_lowerdata_separator, 0, wx.EXPAND, 0)
        nowButton_vertical_sizer.Add(self.bpNow_Button, 2, wx.EXPAND, 0)
        nowButton_vertical_sizer.Add(self.setBPmins_combobox, 1, wx.BOTTOM|wx.EXPAND, 0)

        bp_grid.Add(nowButton_vertical_sizer,1,  4)
        bp_grid.Add(self.bp_pressure, 1, wx.EXPAND, 0)

        nowButton_horizontal_sizer.Add(bp_grid, 1, wx.EXPAND, 0)
        bp_label_sizer.Add(self.bp_label, 1, wx.BOTTOM, 1)
        bp_label_sizer.Add(self.bp_infolabel, 1, wx.BOTTOM|wx.EXPAND, 1)
        bp_sizer.Add(bp_label_sizer, 0, wx.EXPAND, 0)
        sizer_2.Add(self.bpvalue_label, 1, wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_2.Add(self.panel_1, 1, wx.EXPAND|wx.ALIGN_RIGHT, 0)
        sizer_4.Add(sizer_2, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_4, 1, wx.EXPAND, 0)
        bp_sizer.Add(sizer_1, 1, wx.EXPAND, 0)
        bp_sizer.Add(self.bpunit_label, 0, wx.EXPAND, 0)
        nowButton_horizontal_sizer.Add(bp_sizer, 4, wx.RIGHT|wx.TOP|wx.BOTTOM|wx.EXPAND, 4)
        lowerdata_horizontal_sizer.Add(nowButton_horizontal_sizer, 1, wx.EXPAND, 0)
        heartrate_label_sizer.Add(self.heartrate_label, 1, wx.BOTTOM|wx.EXPAND, 1)
        heartrate_label_sizer.Add(self.heartrate_infolabel, 1, wx.BOTTOM|wx.EXPAND, 1)
        heartrate_sizer.Add(heartrate_label_sizer, 0, wx.EXPAND, 0)
        sizer_3.Add(self.bpmvalue_label, 0, wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_3.Add(self.panel_2, 1, wx.EXPAND|wx.ALIGN_RIGHT, 0)
        heartrate_sizer.Add(sizer_3, 1, wx.EXPAND, 0)
        heartrate_sizer.Add(self.bpmunit_label, 0, wx.EXPAND, 0)
        lowerdata_horizontal_sizer.Add(heartrate_sizer, 1, wx.RIGHT|wx.TOP|wx.BOTTOM|wx.EXPAND, 4)
        spo2_label_sizer.Add(self.spo2_label, 1, wx.BOTTOM|wx.EXPAND, 1)
        spo2_label_sizer.Add(self.spo2_infolabel, 1, wx.BOTTOM|wx.EXPAND, 1)
        spo2_sizer.Add(spo2_label_sizer, 0, wx.EXPAND, 0)
        sizer_5.Add(self.spo2value_label, 0, wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_5.Add(self.panel_3, 1, wx.EXPAND|wx.ALIGN_RIGHT, 0)
        spo2_sizer.Add(sizer_5, 1, wx.EXPAND, 0)
        spo2_sizer.Add(self.spo2unit_label, 0, wx.EXPAND, 0)
        lowerdata_horizontal_sizer.Add(spo2_sizer, 1, wx.RIGHT|wx.TOP|wx.BOTTOM|wx.EXPAND, 4)
        main_vertical_sizer.Add(lowerdata_horizontal_sizer, 0, wx.EXPAND, 0)
        self.SetSizer(main_vertical_sizer)
        main_vertical_sizer.Fit(self)
        # end wxGlade

    def onStartStop(self, event): # wxGlade: DAQPanel.<event_handler>
        print "Event handler `onStartStop' not implemented!"
        event.Skip()

    def onRefer(self, event): # wxGlade: DAQPanel.<event_handler>
        print "Event handler `onRefer' not implemented!"
        event.Skip()

    def on12Lead(self, event): # wxGlade: DAQPanel.<event_handler>
        print "Event handler `on12Lead' not implemented!"
        event.Skip()

    def onBPNow(self, event): # wxGlade: DAQPanel.<event_handler>
        print "Event handler `onBPNow' not implemented!"
        event.Skip()

    def onUpload(self, event): # wxGlade: DAQPanel.<event_handler>
        print "Event handler `onUpload' not implemented"
        event.Skip()

    def onCall(self, event): # wxGlade: DAQPanel.<event_handler>
        print "Event handler `onCall' not implemented"
        event.Skip()

# end of class DAQPanel


class ReferPanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ReferPanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.Videoconf_Label = wx.StaticText(self, -1, "Video Conference", style=wx.ALIGN_CENTRE)
        self.Videoconf_Panel = wx.Panel(self, -1)
        self.Photoshot_Label = wx.StaticText(self, -1, "Photo Snapshot", style=wx.ALIGN_CENTRE)
        self.Photoshot_Panel = wx.Panel(self, -1)
        self.static_line_5 = wx.StaticLine(self, -1)
        self.IM_Label = wx.StaticText(self, -1, "Instant Messaging", style=wx.ALIGN_CENTRE)
        self.IMtexts_Text = wx.TextCtrl(self, -1, "", style=wx.TE_PROCESS_ENTER|wx.TE_MULTILINE|wx.TE_READONLY)
        self.IMreply_Text = wx.TextCtrl(self, -1, "", style=wx.TE_PROCESS_ENTER|wx.TE_MULTILINE)
        self.Remarks_Label = wx.StaticText(self, -1, "Remarks", style=wx.ALIGN_CENTRE)
        self.Remarks_Text = wx.TextCtrl(self, -1, "", style=wx.TE_PROCESS_ENTER|wx.TE_MULTILINE)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ReferPanel.__set_properties 620
        self.Videoconf_Label.SetMinSize((400, 20))
        self.Videoconf_Label.SetBackgroundColour(wx.Colour(251, 255, 100))
        self.Videoconf_Label.SetFont(wx.Font(10, wx.MODERN, wx.NORMAL, wx.BOLD, 0, "Arial"))
        self.Videoconf_Panel.SetBackgroundColour(wx.Colour(244, 244, 244))
        self.Photoshot_Label.SetMinSize((400, 20))
        self.Photoshot_Label.SetBackgroundColour(wx.Colour(251, 255, 100))
        self.Photoshot_Label.SetFont(wx.Font(10, wx.MODERN, wx.NORMAL, wx.BOLD, 0, "Arial"))
        self.Photoshot_Panel.SetBackgroundColour(wx.Colour(244, 244, 244))
        self.IM_Label.SetMinSize((400, 20))
        self.IM_Label.SetBackgroundColour(wx.Colour(253, 255, 191))
        self.IM_Label.SetFont(wx.Font(10, wx.MODERN, wx.NORMAL, wx.BOLD, 0, "Arial"))
        self.IMtexts_Text.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.IMreply_Text.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.Remarks_Label.SetMinSize((400, 20))
        self.Remarks_Label.SetBackgroundColour(wx.Colour(253, 255, 191))
        self.Remarks_Label.SetFont(wx.Font(10, wx.MODERN, wx.NORMAL, wx.BOLD, 0, "Arial"))
        self.Remarks_Text.SetBackgroundColour(wx.Colour(255, 255, 255))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ReferPanel.__do_layout
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_13 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_19 = wx.BoxSizer(wx.VERTICAL)
        sizer_14 = wx.BoxSizer(wx.VERTICAL)
        sizer_18 = wx.BoxSizer(wx.VERTICAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_12 = wx.BoxSizer(wx.VERTICAL)
        sizer_11 = wx.BoxSizer(wx.VERTICAL)
        sizer_11.Add(self.Videoconf_Label, 1, wx.RIGHT|wx.EXPAND, 1)
        sizer_11.Add(self.Videoconf_Panel, 8, wx.RIGHT|wx.TOP|wx.EXPAND, 1)
        sizer_10.Add(sizer_11, 1, wx.EXPAND, 0)
        sizer_12.Add(self.Photoshot_Label, 1, wx.LEFT|wx.EXPAND, 1)
        sizer_12.Add(self.Photoshot_Panel, 8, wx.LEFT|wx.TOP|wx.EXPAND, 1)
        sizer_10.Add(sizer_12, 1, wx.EXPAND, 0)
        sizer_6.Add(sizer_10, 5, wx.ALL|wx.EXPAND, 4)
        sizer_6.Add(self.static_line_5, 0, wx.EXPAND, 0)
        sizer_14.Add(self.IM_Label, 1, wx.RIGHT|wx.EXPAND, 1)
        sizer_18.Add(self.IMtexts_Text, 3, wx.TOP|wx.EXPAND, 1)
        sizer_18.Add(self.IMreply_Text, 0, wx.TOP|wx.EXPAND, 4)
        sizer_14.Add(sizer_18, 8, wx.EXPAND, 0)
        sizer_13.Add(sizer_14, 1, wx.EXPAND, 0)
        sizer_19.Add(self.Remarks_Label, 1, wx.LEFT|wx.EXPAND, 1)
        sizer_19.Add(self.Remarks_Text, 8, wx.TOP|wx.EXPAND, 1)
        sizer_13.Add(sizer_19, 1, wx.EXPAND, 0)
        sizer_6.Add(sizer_13, 5, wx.ALL|wx.EXPAND, 4)
        self.SetSizer(sizer_6)
        sizer_6.Fit(self)
        # end wxGlade

# end of class ReferPanel


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    rx_frame = RxFrame(None, -1, "")
    app.SetTopWindow(rx_frame)
    rx_frame.Show()
    app.MainLoop()
