#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Fri Aug 07 23:00:47 2009

import wx

# begin wxGlade: extracode
# end wxGlade



class DeviceDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: DeviceDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.Device_info = wx.StaticText(self, -1, "ECG:\n\nPULSE OX:\n\n\nBLOOD PRESSURE:")
        self.ok_button = wx.Button(self, -1, "OK")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.onOKAY, self.ok_button)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: DeviceDialog.__set_properties
        self.SetTitle("Device Status Check")
        self.Device_info.SetMinSize((395, 228))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: DeviceDialog.__do_layout
        main_sizer = wx.BoxSizer(wx.VERTICAL)
        main_sizer.Add(self.Device_info, 2, wx.EXPAND, 3)
        main_sizer.Add(self.ok_button, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        self.SetSizer(main_sizer)
        main_sizer.Fit(self)
        self.Layout()
        # end wxGlade

    def onOKAY(self, event): # wxGlade: DeviceDialog.<event_handler>
        self.Destroy()

# end of class DeviceDialog


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    device_dialog = DeviceDialog(None, -1, "")
    app.SetTopWindow(device_dialog)
    device_dialog.Show()
    app.MainLoop()
