#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Mon Aug 23 20:04:22 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class SPO2Panel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SPO2Panel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.heartrate_label = wx.StaticText(self, -1, "Heart Rate", style=wx.ALIGN_CENTRE)
        self.heartrate_infolabel = wx.StaticText(self, -1, "HeartRate Unavailable:Check Connections")
        self.bpmvalue_label = wx.StaticText(self, -1, "--", style=wx.ALIGN_CENTRE)
        self.bpmrightpanel = wx.Panel(self, -1)
        self.bpmunit_label = wx.StaticText(self, -1, "bpm", style=wx.ALIGN_RIGHT)
        self.heartrate_staticline = wx.StaticLine(self, -1, style=wx.LI_VERTICAL)
        self.spo2_label = wx.StaticText(self, -1, "Blood Oxygen Saturation", style=wx.ALIGN_CENTRE)
        self.spo2_infolabel = wx.StaticText(self, -1, "% Oxygen Unavailable:Check Connections")
        self.spo2value_label = wx.StaticText(self, -1, "--", style=wx.ALIGN_CENTRE)
        self.spo2rightpanel = wx.Panel(self, -1)
        self.spo2unit_label = wx.StaticText(self, -1, "%SpO2", style=wx.ALIGN_RIGHT)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: SPO2Panel.__set_properties
        self.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.heartrate_label.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.heartrate_label.SetFont(wx.Font(9, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.heartrate_infolabel.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.heartrate_infolabel.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.bpmvalue_label.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.bpmvalue_label.SetFont(wx.Font(30, wx.MODERN, wx.NORMAL, wx.BOLD, 0, "Arial"))
        self.bpmrightpanel.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.bpmunit_label.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.bpmunit_label.SetFont(wx.Font(10, wx.MODERN, wx.NORMAL, wx.BOLD, 0, "Arial"))
        self.spo2_label.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.spo2_label.SetFont(wx.Font(9, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.spo2_infolabel.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.spo2_infolabel.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.spo2value_label.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.spo2value_label.SetFont(wx.Font(30, wx.MODERN, wx.NORMAL, wx.BOLD, 0, "Arial"))
        self.spo2rightpanel.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.spo2unit_label.SetBackgroundColour(wx.Colour(226, 255, 180))
        self.spo2unit_label.SetFont(wx.Font(10, wx.MODERN, wx.NORMAL, wx.BOLD, 0, "Arial"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: SPO2Panel.__do_layout
        spo2_panel_sizer = wx.BoxSizer(wx.HORIZONTAL)
        spo2_sizer = wx.BoxSizer(wx.VERTICAL)
        spo2labelsizer = wx.BoxSizer(wx.HORIZONTAL)
        spo2_label_sizer = wx.BoxSizer(wx.HORIZONTAL)
        heartrate_sizer = wx.BoxSizer(wx.VERTICAL)
        bpmlabelsizer = wx.BoxSizer(wx.HORIZONTAL)
        heartrate_label_sizer = wx.BoxSizer(wx.HORIZONTAL)
        heartrate_label_sizer.Add(self.heartrate_label, 2, wx.BOTTOM|wx.EXPAND, 1)
        heartrate_label_sizer.Add(self.heartrate_infolabel, 3, wx.BOTTOM|wx.EXPAND, 1)
        heartrate_sizer.Add(heartrate_label_sizer, 0, wx.EXPAND, 0)
        bpmlabelsizer.Add(self.bpmvalue_label, 1, wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        bpmlabelsizer.Add(self.bpmrightpanel, 1, wx.EXPAND, 0)
        heartrate_sizer.Add(bpmlabelsizer, 1, wx.EXPAND, 0)
        heartrate_sizer.Add(self.bpmunit_label, 0, wx.ALIGN_RIGHT, 0)
        spo2_panel_sizer.Add(heartrate_sizer, 1, wx.EXPAND, 0)
        spo2_panel_sizer.Add(self.heartrate_staticline, 0, wx.EXPAND, 0)
        spo2_label_sizer.Add(self.spo2_label, 2, wx.BOTTOM|wx.EXPAND, 1)
        spo2_label_sizer.Add(self.spo2_infolabel, 3, wx.BOTTOM|wx.EXPAND, 1)
        spo2_sizer.Add(spo2_label_sizer, 0, wx.EXPAND, 0)
        spo2labelsizer.Add(self.spo2value_label, 1, wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        spo2labelsizer.Add(self.spo2rightpanel, 1, wx.EXPAND, 0)
        spo2_sizer.Add(spo2labelsizer, 1, wx.EXPAND, 0)
        spo2_sizer.Add(self.spo2unit_label, 0, wx.ALIGN_RIGHT, 0)
        spo2_panel_sizer.Add(spo2_sizer, 1, wx.EXPAND, 0)
        self.SetSizer(spo2_panel_sizer)
        spo2_panel_sizer.Fit(self)
        # end wxGlade

# end of class SPO2Panel


